### ISSUE TITLE
[BDW][Media][Decode]YamiUnitTest  JPEG decoding ssim value is low  

### ISSUE THREAD

**Issue by wenxin2** [01org/libyami#108]
1.Testing Env:
libva:                             (master) c356638098e55453d2fac8bbb92eafc8cc32d6f4
intel driver:                 (staging)98b28c5b4e7f6c00270dd146974be97ce6f321f4         
libyami:                        (master) ea0c74298dcaa3d7f75261df98cfa31895bf9089
omxil-core:                  (master) d6f6edef3119d5622f9066521fc4b53004410a27
omx-components:     (master) 464135af23ac7d3ae5d3a9240f2fd7a058eb2d7c
gst-omx:                      (master) f178afe59e507ea7113bbc630affd6d502a2418c

2.Test command:
   (1)use following command to get dump yuv file
      /home/zliu50x/libyami/omx/libyami/tests/yamidecode -i /home/workdir.jpeg_dec/1080p_blue_sky.yuv.jpg -m 0 -f I420
  (2)use following command to get reference yuv' file
       gst-launch-1.0 filesrc location=/home/workdir.jpeg_dec/1080p_blue_sky.yuv.jpg '!' 'jpegparse!' jpegdec '!' videoconvert '!' video/x-raw, format=I420 '!' filesink location=dump.yuv
 (3)compare yuv and yuv' file to get ssim. and find ssim value is low
yuv filename 	                y_min_ssim  y_ave_ssim u_min_ssim u_ave_ssim v_min_ssim v_ave_ssim	
1080p_blue_sky.yuv.jpg 	0.997193	     0.997702	  0.979815       0.986921   0.985011      0.991386	
MOBILE_352x288_30_orig_01.yuv.jpg 0.999048	0.999239	0.983513	0.985694	0.983802	0.985874

**Comment by YuJiankang** [comment]
Checked the jpeg conformance test spec. Suggested QA to try the better way to check the quality of jpeg decoder
                a)Each coded stream is decoded using the decoder under test.
                b)Difference between the decoded outputs and original reference YUV image are measured
                c)add more test stream to increase the test coverage
               d)YUV image decoded by libyami should be exactly matched with image decoded by reference player with same Intel driver
                with the new test method, all the test passed.

**Comment by wenxin2** [comment]
yes, it is ok now
