### ISSUE TITLE
decodecapi can't playback when use render mode 2/3/4/5

### ISSUE THREAD

**Issue by changzhix** [01org/libyami#117]
decodecapi -i /path/to/h264 -m 2/3/4/5
When use render mode 2/3/4/5, there is an error：
decodehelp.h:358 renderOutputFrames: Assertion ‘0’ failed.

**Comment by andyLiuChina** [comment]
non-reproducible bug

**Comment by keqiaox** [comment]
Hi Guangxin,

 I have tested this issue with the latest driver, it's OK with render mode 2/3/4, but not OK with mode 5, print screen as "lt-decodecapi: decodeoutput.cpp:634: static DecodeOutput* DecodeOutput::create(YamiMediaCodec::IVideoDecoder*, int): Assertion `0 && "do not support this render mode"' failed.
Aborted (core dumped)"

**Comment by andyLiuChina** [comment]
Do not support mode 5 at the present time, it is no need to test mode 5.

**Comment by keqiaox** [comment]
If so, it's OK to close this bug.
