### ISSUE TITLE
[BDW][Media][Decode]segmentation fault when doing yamidecode for .mp4 with no render (-m -1)

### ISSUE THREAD

**Issue by wenxin2** [01org/libyami#169]
1.Test Env:
Libva:                                (master)e97ac9e78cd475a13e722c455e34d5d39d0f059d
Libva_intel_driver:             (master)43bd81abdde40b50ac71f6f44eb04e4eaf5af5f6
Libyami:                             (master)8cc7e42ca49ea407b7e49db0e200f794e20fc49c

2.Test command:
(1)use following command to get dump yuv file 
/home/wenxin1/libyami/omx/libyami/tests/yamidecode -i /media/ts/H264_176x144_frame320.mp4 -m -1
the messege is here:
input file: /media/ts/H264_176x144_frame320.mp4, renderMode: -1
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/X11R7/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
Segmentation fault

**Comment by xuguangxin** [comment]
fix by a72bff04b08d679d7a478aa2de0dcf4d2af8d353
