### ISSUE TITLE
[BDW][Media][Decode]libyami can not work when doing v4l2decode for .mp4 format with (-m 0/3/4)

### ISSUE THREAD

**Issue by wenxin2** [01org/libyami#170]
1.Test Env:
Libva: (master)e97ac9e78cd475a13e722c455e34d5d39d0f059d
Libva_intel_driver: (master)43bd81abdde40b50ac71f6f44eb04e4eaf5af5f6
Libyami: (master)8cc7e42ca49ea407b7e49db0e200f794e20fc49c

2.Test command:
(1)use following command to get dump yuv file 
/home/wenxin1/libyami/omx/libyami/tests/v4l2decode -i /media/ts/H264_176x144_frame320.mp4 -m 0
the result is that:
libyami can not work

**Comment by xuguangxin** [comment]
similar issue as [BDW][Media][Decode]yamidecode blocks at XGetWindowAttributes() after libva dlopen #168
we will look at this after it's fixed.

**Comment by xuguangxin** [comment]
Can we close this since #168 closed,

**Comment by xuguangxin** [comment]
Hi @keqiaox
Can we close this,Or you have update on this?

**Comment by keqiaox** [comment]
Hi Guangxin,

 After tested with andy's patch, this issue doesn't exists. so close this bug.
