### ISSUE TITLE
lack of const

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#175]
in  VideoDecoder class
    virtual const VideoRenderBuffer* getOutput(bool draining = false) = 0;
it return "const " value,but
    virtual void renderDone(VideoRenderBuffer * renderBuf);
has no "const".

**Comment by YuJiankang** [comment]
This issue is fixed by the the following commit, patch is merged to trunk code.
bc55f96e12e758f70f84e63eeed7ef2f278f43c0

**Comment by xuguangxin** [comment]
thanks waiter89 & Jiankang
