### ISSUE TITLE
VC-1 (VC1) and WMV 9 (WMV3) support missing

### ISSUE THREAD

**Issue by Hedda** [01org/libyami#176]
Request SMPTE decoder support for VC-1 (VC1/WVC1) and Windows Media Video 9 (WMV3) decode:

http://en.wikipedia.org/wiki/VC-1

SMPTE 421M, informally known as VC-1, is a video coding format. It was initially developed as a proprietary video format based on WMV 9 (Windows Media Video 9) by Microsoft in 2003 and officially approved as a SMPTE video codec standard on April 3, 2006. VC-1 is today a supported standard found in the Blu-ray Disc specification, Microsoft's Silverlight framework, and the now-discontinued HD-DVD.

**Comment by xuguangxin** [comment]
Our first priority are vp9 and hevc. VC1 is in our todo list. But it's not gonna be in next release. If you have strong request for this, we can rearrange our priority. But its not a promise. 
Other option is someone help us to implement is ;). We treat mpeg2/mpeg4/vc1 as legacy codec. We have codec parser for them but no decoder implement yet. Codec parser done  most of dirty things. The decoder should less than 400 line like https://github.com/01org/libyami/blob/master/decoder/vaapidecoder_vp9.cpp does.

**Comment by Hedda** [comment]
Yes I would strongly recommend prioritizing VC-1 (WMV9) over HEVC (H.265) right now because the are so many more real-world examples out there of VC-1 encoded video compared to available HEVC videos.

One perfect example is that approximately 10-20% of all Blu-Ray Disc movies that have been sold are are still being sold are encoded in  VC-1 (WMV9). So while you can still playback 80-90% of all  Blu-Ray Disc media that are encoded with the more popular H.264 coded it is still very bad to not being able to playback 1-2 out 10. 

I would argue that based on real-world usage and media available the priority should have been:

First = H.264 (arguable the most used codec today, but with MPEG-2 still being a close second).
Second = MPEG-2 (with hardware deinterlace support to decode 1080i interlaces videos).
Third = VP8 and VP9 (Because they are now being used by HTML5 with sites like YouTube)
Forth = VC-1 (Third popular simply because it is in the Blu-ray Disc standard broad availability).
Fifth = HEVC (Because it will be used in Blu-ray Disc 2.0 and UHD broadcasts later this year)

**Comment by xuguangxin** [comment]
We put vp9 and hevc to high priority base on our hardware spec. And also there are requests from customer, google need vp9, video surveillance customer need hevc. 
mpeg2 is most head ache format. The spec is too old. There are many existed encoders will generate error streams. We need workaround them. It's hard to implement a robust mpeg2 decoder. So we will put this after VC1.

**Comment by xuguangxin** [comment]
Hi Hedda:
Ok, we start to work on vc1 decoder, it should finish all conformance test in 2-3 weeks. Hope it not block you.

**Comment by Hedda** [comment]
Thanks! What is you reference hardware and devices for YAMI/libyami?

**Comment by xuguangxin** [comment]
We use Haswell, but it should work on 
  * Intel Sandybridge, Ivybridge, Haswell and Broadwell (HD Graphics)
  * Intel Baytrail

**Comment by xuguangxin** [comment]
Hi Hedda:
Sorry, we always have other things to interrupt this. And we may not have enough resource to add this in recently. I will notify you if we have fixed this.
BR.

**Comment by xuguangxin** [comment]
we will reopen this after we get time to implements vc1 decoder.
thanks Hedda.

**Comment by Hedda** [comment]
Time to reopen? ...Why? Again, VC-1 is part of the Blu-ray Disc specification standard for BD-ROM.

_For Blu-ray Disc hardware, all players are required to support decodingH.262/MPEG-2 Part 2, H.264/MPEG-4 Part 10: AVC, and SMPTE VC-1. BD-ROM titles with video must store video using one of the three mandatory formats; multiple formats on a single title are allowed. _

Regardless, I think that you should keep this issue open for tracking puposes.

Maybe you will not prioritize to add this yourself, but if someone else notice that this is an open ticket then they could offer to pick it up and submit a pull request.

**Comment by xuguangxin** [comment]
Ok, sorry for long waiting. actually we have plan for this now. It should finished in mid of Q2. But, again, it's not promise.;)

**Comment by seanvk** [comment]
Supported now upstream.
