### ISSUE TITLE
[SKL][Media][Encode]fps value was set  error when doing vp8 encoding test

### ISSUE THREAD

**Issue by wenxin2** [01org/libyami#180]
1.Testing environment:
libva:                             (staging) d9626b77f865ce7bdbc8c78988a86d3e4f55d67b
intel driver:                    (staging) a8ca5f911c7c19b5ede3f96ac6113606b9dd4d95
libyami:                          (master) 7730d21bcbcc6511f86bfc74ec7e6763c76dcae5
omxil-core:                     (master) d6f6edef3119d5622f9066521fc4b53004410a27
omx-components:          (master) 464135af23ac7d3ae5d3a9240f2fd7a058eb2d7c
gst-omx:                         (master) f178afe59e507ea7113bbc630affd6d502a2418c
2.Test command
(1)/home/zliu50x/libyami/omx/libyami/tests/yamiencode -i /home/encoderbitstreams/encoderbitstreams/1080p_blue_sky.yuv -s I420 -W 1920 -H 1080 -c VP8 -o 1080p_blue_sky.yuv.enc.vp8
(2)using vega test tools to verify the correctness,found that carton occurred while playing the file.The fps value was set  error when doing vp8 encoding test.

**Comment by andyLiuChina** [comment]
fixed by  8b999407572209d88a143331f31002d279fed0fa
