### ISSUE TITLE
[SKL][media][Encode] frame numbers in the head of file are not same with real frames

### ISSUE THREAD

**Issue by wenxin2** [01org/libyami#181]
1.Testing environment:
libva:                          (staging) d9626b77f865ce7bdbc8c78988a86d3e4f55d67b
intel driver:                 (staging) a8ca5f911c7c19b5ede3f96ac6113606b9dd4d95
libyami:                       (master) 7730d21bcbcc6511f86bfc74ec7e6763c76dcae5
omxil-core:                  (master) d6f6edef3119d5622f9066521fc4b53004410a27
omx-components:       (master) 464135af23ac7d3ae5d3a9240f2fd7a058eb2d7c
gst-omx:                      (master) f178afe59e507ea7113bbc630affd6d502a2418c
.2.Test command
(1)/home/zliu50x/libyami/omx/libyami/tests/yamiencode -i /home/encoderbitstreams/encoderbitstreams/1080p_blue_sky.yuv -s I420 -W 1920 -H 1080 -c VP8 -o 1080p_blue_sky.yuv.enc.vp8
(2)using vega test tools to verify the correctness,found frame numbers in the head of file were not same with real frames

**Comment by andyLiuChina** [comment]
fixed by d230ae1778b41dad962160f2cf9f866911d9622b

**Comment by lizhong1008** [comment]
@andyLiuChina update a patch to set the frame_num in ivf header. However, the frame_num in ivf header is larger than the set frame number: "yamiencode -N"
I have given a patch to fix this issue and waiting for review: https://github.com/lizhong1008/libyami/commit/9cb9b67972c70d93db4df68c56d89ef457f69b7e

**Comment by xuguangxin** [comment]
merged to master

**Comment by lizhong1008** [comment]
@wenxin2 , can this issue be closed now?

**Comment by wenxin2** [comment]
Yes,it is ok now.
