### ISSUE TITLE
[SKL][Media][Encode]corrupt occured when doing vp8 encoding test for MOBILE_352x288_30_orig_01.yuv 

### ISSUE THREAD

**Issue by wenxin2** [01org/libyami#182]
1.Testing environment:
libva:                          (staging) d9626b77f865ce7bdbc8c78988a86d3e4f55d67b
intel driver:                 (staging) a8ca5f911c7c19b5ede3f96ac6113606b9dd4d95
libyami:                       (master) 7730d21bcbcc6511f86bfc74ec7e6763c76dcae5
omxil-core:                  (master) d6f6edef3119d5622f9066521fc4b53004410a27
omx-components:       (master) 464135af23ac7d3ae5d3a9240f2fd7a058eb2d7c
gst-omx:                      (master) f178afe59e507ea7113bbc630affd6d502a2418c
2.Test command
(1) /home/zliu50x/libyami/omx/libyami/tests/yamiencode -i /home/encoderbitstreams/encoderbitstreams/MOBILE_352x288_30_orig_01.yuv -s I420 -W 352 -H 288 -c VP8 -o MOBILE_352x288_30_orig_01.enc.vp8
(2)corrupt occured when doing vp8 encoding test for a while

**Comment by andyLiuChina** [comment]
fixed by 2684c8d66d802fc364af785e9c5235293fd12d1b

**Comment by wenxin2** [comment]
it is ok .
