### ISSUE TITLE
vaPutSurface flags

### ISSUE THREAD

**Issue by jsorg71** [01org/libyami#206]
We need a way to pass a value to the last parameter of vaPutSurface.
Currently, you always hard code a zero.
See VaapiDecoderBase::getOutput.
I can do a pull request but I want to know how you prefer to do this.
Options include.

1 - add a parameter to the function calls ie VaapiDecoderBase::getOutput.  This will touch many files.
2 - add a class member to "class VaapiDecoderBase"  Someting like
public:
  unsigned int m_putSurfaceFlags;
3 - some other idea I didn't think about, let me know.

Currently, I prefer option 2.

Jay

**Comment by xuguangxin** [comment]
Hi Jay:
which flag you want use, Is it gone dynamic change?

**Comment by jsorg71** [comment]
VA_SRC_BT601 and VA_SRC_BT709
RemoteFX H264 uses VA_SRC_BT709 which is not default.
I currently have to patch this and ship a modified libyami.
I guess it does not need to be dynamic but I can see the possible need.

**Comment by xuguangxin** [comment]
If you use option 2, you still need a function to set the m_putSurfaceFlags. and this function is not needed by other getOutput. 
Maybe, option 1 is better. you do not need modify too many file since you can use default param.
just like  frameX.

By The Way, in middle term. We want getOutput only output VaSurface(with some wrapper). You can do what you want when you get the surfacd id.

**Comment by jsorg71** [comment]
Ok, I'll create a PR.

**Comment by xuguangxin** [comment]
thanks

**Comment by xuguangxin** [comment]
Hi Jay:
we have new interface SharedPtr<VideoFrame>IVideoDecoder::getOutput(), VideoFrame.surface is a VASurface. So you can use it do any thing you want. You can see https://github.com/01org/libyami/blob/master/examples/simpleplayer.cpp for usage.

thanks

**Comment by jsorg71** [comment]
@xuguangxin Thanks, I'll check it out.

**Comment by xuguangxin** [comment]
Hi @jsorg71 :
How was this goingon?

thanks

**Comment by jsorg71** [comment]
@xuguangxin 

I'm using the capi.
Here is some sample code how I'm using the decode and vaPutSurface.
This works great and I have access to all the capabilities of vaPutSurface.

Jay

    memset(&ib, 0, sizeof(ib));
    ib.data = cdata;
    ib.size = cdata_bytes;
    status = g_decode(self->dec, &ib);
    if (status == 2) /* DECODE_FORMAT_CHANGE */
    {
        fi = g_getFormatInfo(self->dec);
        status = g_decode(self->dec, &ib);
    }
    if (status == 1) /* DECODE_SUCCESS */
    {
        rb = g_decodeGetOutput(self->dec, 1);
        if (rb != 0)
        {
            status = g_vaPutSurface(rb->display, rb->surface, pixmap,
                                    0, 0, src_width, src_height,
                                    0, 0, dst_width, dst_height,
                                    0, 0, flags);
            if (status != 0) /* != VA_STATUS_SUCCESS */
            {
                rv = 3;
            }
            g_renderDone(self->dec, rb);
        }
        else
        {
            rv = 4;
        }
    }
    else
    {
        rv = 2;
    }
    return rv;

**Comment by xuguangxin** [comment]
great! so I will close this issue.

**Comment by xuguangxin** [comment]
thanks Jay
