### ISSUE TITLE
[BDW][Media][Decode/Encode]The usage information of yamivpp feature is not comprehensive and not detailed 

### ISSUE THREAD

**Issue by wenxin2** [01org/libyami#228]
1.Testing environment:
Libva:                      (master)4763db1c2133d4e6b92355938ecb6f23a7767b6b
Libva_intel_driver:   (master)4a1c4d21f3428b08ef765d7f7de75b97006514ac
libyami:                    (master)5c64c7237e06e41d0c64b4bc97c5d74900531786
 2.Test command
 (1) /home/wenxin/libyami/libyami/tests/yamivpp -h
usage: yamivpp input_1920x1080.i420 output_320x240.yv12
(2) there are little detailed information for VPP.

**Comment by xuguangxin** [comment]
HI Keqiao:
it's fixed by #291. Please help to verify.
thanks

**Comment by keqiaox** [comment]
hi Guangxin,

 After verified, the usage for yamivpp is detailed now, list as following:
./yamivpp -h
a tool to do video post process, support scaling and CSC
we can guess size and color format from your file name
current supported format are i420, yv12, nv12
usage: yamivpp input_1920x1080.i420 output_320x240.yv12

so this bug can be closed.
