### ISSUE TITLE
[BDW][Media][Decode/Encode]some relevant package for build libyami should be detailed expecially when adding the parameter --enable-gles

### ISSUE THREAD

**Issue by wenxin2** [01org/libyami#229]
1.Testing environment:
 Libva: (master)4763db1c2133d4e6b92355938ecb6f23a7767b6b
 Libva_intel_driver: (master)4a1c4d21f3428b08ef765d7f7de75b97006514ac
 libyami: (master)5c64c7237e06e41d0c64b4bc97c5d74900531786
 2.Test command
 (1) the steps of build for libyami
git clean -dxf && ./autogen.sh --prefix=$LIBYAMI_PREFIX --enable-tests --enable-tests-gles && make -j8 && make install
(2)check the build result
/home/wenxin/libyami/libyami/tests/decodeoutput.cpp:486: undefined reference to `glEGLImageTargetTexture2DOES'
/home/wenxin/libyami/libyami/tests/decodeoutput.cpp:491: undefined reference to `eglDestroyImageKHR'
gles2_help.o: In function `createTextureFromPixmap':
/home/wenxin/libyami/libyami/tests/./egl/gles2_help.c:85: undefined reference to `eglCreateImageKHR'
/home/wenxin/libyami/libyami/tests/./egl/gles2_help.c:88: undefined reference to `glEGLImageTargetTexture2DOES'
egl_util.o: In function `createEglImageFromDrmBuffer':
/home/wenxin/libyami/libyami/tests/../egl/egl_util.c:47: undefined reference to `eglCreateImageKHR'
collect2: error: ld returned 1 exit status
make[2]: *** [yamidecode] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/vpp.Tpo .deps/vpp.Po
make[2]: Leaving directory `/home/wenxin/libyami/libyami/tests'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/wenxin/libyami/libyami'
make: *** [all] Error 2

**Comment by zhongcong** [comment]
wenxin, maybe your libyami pkg-config find the egl.pc and glesv2.pc.
But the egl and glesv2 library location is not right.
Pls check again.

**Comment by uartie** [comment]
Newer versions of Mesa don't have these defined in their symbol table... we need to use eglGetProceAddress instead.  I have a patch in the pipline...

**Comment by zhongcong** [comment]
#252 can fix this issue, @xuguangxin will you add this patch into libyami?
