### ISSUE TITLE
Add "Contributing" section to README

### ISSUE THREAD

**Issue by uartie** [01org/libyami#235]
A "Contributing" section in the README would advertise to developers the expected method for contributing patches to this project, even if it seems obvious.  Also, is there a mailing list for this project?

**Comment by chivakker** [comment]
mailing list is libyami@lists.01.org

**Comment by xuguangxin** [comment]
good suggestion done at https://github.com/01org/libyami/commit/2170aa04aa90df422702f59a8e5cbf1e868af8db

**Comment by xuguangxin** [comment]
thanks uartie and Daniel

**Comment by xuguangxin** [comment]
close since it fix
