### ISSUE TITLE
[media][Encode]Green block appeared when using VEGA tools to playback H264 CQP 4K encoded bitstream,set qp=7

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#264]
![4k](https://cloud.githubusercontent.com/assets/13446640/8868153/90a9240a-3206-11e5-802d-688c6d93821d.PNG)
1.Testing environment:
 Libva: (master)70b80c0dd2effb4956b208775641f7c68a67a9df
Libva_intel_driver: (master)611d8ea9d75dc026c203e3ebe53b434769d4587c
libyami: (master) 0cfc3a48e6eb4af3adc437879f082351a0cff2b2
 ffmpeg: (master) da8b70b810bb2703f976d737af8c68d35716f5ea
2.Test command:
1.$/home/yami/libyami/libyami/tests/yamiencode -i /media/encoderbitstreams/4K_2013_3840_2160_300frames.yuv -s I420 -W 3840 -H 2160 --qp 7 -c AVC --rcmode CQP -o /home/yami/h264/h264_cqp/4K_2013_3840_2160_300frames.yuv_7.h264
2.$/home/yami/libyami/libyami/tests/yamidecode -i /home/yami/h264/h264_cqp/4K_2013_3840_2160_300frames.yuv_7.h264 -m 0 -f I420 -o ./h264_cqp_I420/

**Comment by lizhong1008** [comment]
I try to use libva test case "avcenc" to encode this yuv video, and set qp=7:
 avcenc 3840 2160 4K_2013_3840_2160_300frames.yuv avcenc_4k_qp7_level52.h264 qp=7 mode=1
The encoded frame_number of 187 also have green block.
So I think it's a libva-intel-driver bug, not libyami. My suggestion is closing this issue and firing a bug to libva-intel-driver.

**Comment by lizhong1008** [comment]
Hi @keqiaox @wenxin2 : How about close this issue and file a bug to libva project?

**Comment by keqiaox** [comment]
hi zhong,

 I can also duplicated this issue with libva intel driver, so I will close this bug and open a new one for libva driver.

Thanks~
