### ISSUE TITLE
[HSW][media][Encode]error message "Unexpected byte value after Emulation byte .found 30 allowed 0,1,2,3"  appeared after using VEGA tool to playback H264 cqp encode bitstream

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#265]
1.Testing environment:
libva: (staging) d9626b77f865ce7bdbc8c78988a86d3e4f55d67b
intel driver: (staging) a8ca5f911c7c19b5ede3f96ac6113606b9dd4d95
libyami: (master) 7730d21
omxil-core: (master) d6f6edef3119d5622f9066521fc4b53004410a27
omx-components: (master) 464135af23ac7d3ae5d3a9240f2fd7a058eb2d7c
gst-omx: (master) f178afe59e507ea7113bbc630affd6d502a2418c

2. Test command:
 use VEGA tool to playback the bitstreams

3.Result:
  error log appeared :
  "Unexpected byte value after Emulation byte .found 30 allowed 0,1,2,3"
4. Related bitstreams:
720x480p.yuv_7.h264
720x480p.yuv_14.h264
720x480p.yuv_21.h264
720x480p.yuv_35.h264
720x480p.yuv_42.h264
720x480p.yuv_49.h264
CITY_704x576_30_orig_01.yuv_21.h264
CITY_704x576_30_orig_01.yuv_28.h264
CITY_704x576_30_orig_01.yuv_35.h264
CITY_704x576_30_orig_01.yuv_49.h264
V007383_Wall_walkers_176_144p_25fps_371frames.yuv_21.h264
V007383_Wall_walkers_176_144p_25fps_371frames.yuv_28.h264
V007383_Wall_walkers_176_144p_25fps_371frames.yuv_35.h264
V007383_Wall_walkers_176_144p_25fps_371frames.yuv_42.h264
V007383_Wall_walkers_176_144p_25fps_371frames.yuv_49.h264

**Comment by lizhong1008** [comment]
Create a commit to fix this issue: lizhong1008@4612f42
Waiting for review.

**Comment by xuguangxin** [comment]
hi keqiao:
it's merged. Please help to verify if you have time

**Comment by keqiaox** [comment]
Hi Guangxin,
 After re-testing these cases with the latest commit, did not found this issue,so close the bug.
