### ISSUE TITLE
[HSW][media][Encode]error message "Compression ratio found 2.54 in Access Unit for level 4.0 ..." appeared after using VEGA tool to playback H264 cqp encode bitstream

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#266]
1.Testing environment:
libva: (staging) d9626b77f865ce7bdbc8c78988a86d3e4f55d67b
intel driver: (staging) a8ca5f911c7c19b5ede3f96ac6113606b9dd4d95
libyami: (master) 7730d21
omxil-core: (master) d6f6edef3119d5622f9066521fc4b53004410a27
omx-components: (master) 464135af23ac7d3ae5d3a9240f2fd7a058eb2d7c
gst-omx: (master) f178afe59e507ea7113bbc630affd6d502a2418c

2.Test command: 
    use VEGA tool to playback the bitstreams
3.Result:
   error log appeared :
   "Compression ratio found 2.54 in Access Unit for level 4.0 .allowed Min compression        ratio(MinCR)is 4. coded bits=4358856 Uncompressed bits =11059200"
4. Related bitstreams:
   OBILE_352x288_30_orig_01.yuv_7.h264
   MOBILE_352x288_30_orig_01.yuv_14.h264
   MOBILE_352x288_30_orig_01.yuv_21.h264
   V007383_Wall_walkers_176_144p_25fps_371frames.yuv_7.h264
   V007383_Wall_walkers_176_144p_25fps_371frames.yuv_14.h264

**Comment by lizhong1008** [comment]
Create a commit to fix this issue: https://github.com/lizhong1008/libyami/commit/4612f42589430fdda48e8c4fadf7e6fa13946f11
Waiting for review.
