### ISSUE TITLE
vp9 ref_frame_sign_bias flag set error.

### ISSUE THREAD

**Issue by zhongcong** [01org/libyami#273]
in some vp9 clips,  ref_frame_sign_bias_flag set error.
clip: Stress_VP9_3840x2160_150_inter_stress_1.1.vp9

**Comment by zhongcong** [comment]
Find out that libyami should set ref_frame_sing_bias to zero when Reset the segment feature data to the default stats but libyami forget that.

**Comment by zhongcong** [comment]
see #275 , this bug is fixed.

**Comment by xuguangxin** [comment]
Hi Cong:
can we close this?

**Comment by zhongcong** [comment]
yes, it can be closed now.
