### ISSUE TITLE
H264 decode demo,ColorConvert :: NV12ToI420 very Low Performance

### ISSUE THREAD

**Issue by bluceldg** [01org/libyami#274]
When I use the tests / decode.cpp, decoding H264 (1280 * 960) video, and output yuv file , the process and the results are normal, but ColorConvert :: NV12ToI420 very Low Performance, I do the conversion using ffmpeg's sws_scale, the same efficiency has not improved significantly. Tests found the problem is that memcpy with the pointer vaMapBuffer        
     I used to do hard libav11.4 test solution on the same device, the result is 2-3 milliseconds decoded and converted into a frame of data
     I think I may have details of the deal have not taken into account, would you please give me help, thank you!

**Comment by xuguangxin** [comment]
Hi Bluceldg:
The NV12ToI420 is only for  conformance test. to verify decoder result.You should use IVideoPostProcess api to do vpp things.

**Comment by xuguangxin** [comment]
close this since it is not issue
