### ISSUE TITLE
vp9: SegmentationInfoData mistake

### ISSUE THREAD

**Issue by zhongcong** [01org/libyami#277]
clip: Stress_VP9_3840x2160_208_extra_lossless_stress_1.1.vp9

**Comment by zhongcong** [comment]
find the root : SegmentationInfoData mistake, after fix this, all clips can pass except the core dump clips.

**Comment by zhongcong** [comment]
see #279 , this issue is fixed.

**Comment by xuguangxin** [comment]
Hi cong:
can we close this?

**Comment by zhongcong** [comment]
yes, it can be closed now.
