### ISSUE TITLE
[media][decode] Green screen appeared when doing multisession test+ render with 720P 

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#280]
1.Bug detailed description:
  Green screen appeared when we were doing multisession decode and render test with 720P, but 3x3 and 6x6 sessions have not found this issue.
2.Testing environment:
  Libva: (master)70b80c0dd2effb4956b208775641f7c68a67a9df
  Libva_intel_driver: (master)611d8ea9d75dc026c203e3ebe53b434769d4587c
  libyami: (master) edec75e19a7aea126654064abe8ae387c6e0e6ba
  ffmpeg: (master)  e322b7061f873e8fd33b9e518caa19b87616a528

3.Test command: 
 ./grid -c 5 -r 5 $filename 
4.Result:
Green screen appeared

5. Related bitstreams:
LRO-spintest-20Mbs-1280x720-30fps.webm
tears-of-steel-720p-30fps_VP8.webm
msl_launch_720_h264bp_24fps.mp4
H264_1280x720_frame5581.mpeg

**Comment by xuguangxin** [comment]
Hi Keqiao:
Tried this on 1080 display, it do not have this problem. Do I need get 4k display?

**Comment by xuguangxin** [comment]
HI @keqiaox 
can not reproduce on my board, can you check it?

**Comment by keqiaox** [comment]
hi Guangxin,

 After verified, this issue only happens on SKL platform, no issue found on BSW.

**Comment by xuguangxin** [comment]
it's a driver issue. so close it
