### ISSUE TITLE
Libyami does not support specifying the number of frames to be decoded

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#284]
Current libyami does not support this function.so the result get from libyami does not match with the reference values.

**Comment by xuguangxin** [comment]
Hi keqiao:
it fixed by 73b2078a6b5412df2e24af430bea4c5ac9288065.
please have a try.

**Comment by keqiaox** [comment]
hi Guangxin,

  It's OK now,yamidecode can get the right MD5 values mostly with the specific number of frames.But error messages appear when decoding, the messages show:"libyami error(vaapidecoder_base.cpp, 329): surface pool is not initialized yet " .

**Comment by xuguangxin** [comment]
Hi Keqiao:
it's not cause by this commit. So I will close this issue.Please help to create other issue for "surface pool is not initialized yet "
thanks.
