### ISSUE TITLE
[media][decode] 1 AVC clips' MD5 values are not the same as the reference data, decode 50 frames

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#286]
1.Testing environment:
Libva: (master)70b80c0dd2effb4956b208775641f7c68a67a9df
Libva_intel_driver: (master)611d8ea9d75dc026c203e3ebe53b434769d4587c
libyami: (master) 73b2078a6b5412df2e24af430bea4c5ac9288065
ffmpeg: (master) da8b70b810bb2703f976d737af8c68d35716f5ea
2.Test command:
   1.$ ./yamidecode -i /media/avc_vpg/$filename  -m 0 -n 50 -f I420
   2.$ md5sum $filename.I420
3.Failed cases:
    1.blue_sky_420_1280x720.264 
     2.pedestrian_area_420_720x576.264 
     3.V30313_B_D-Traffic_AVC_MP_num_ref_frames_6.264
     4.V30320_A_D-Traffic_AVC_MP_frame_cropping_2x2.264 
     5.V30345_B_D-Traffic_AVC_MP_combination.264
     6.MR6_BT_B.264
     7.MR8_BT_B.264 
     8.sunflower_420_1920x1080.264

**Comment by xuguangxin** [comment]
@clearlylin , could you update this

**Comment by clearlylin** [comment]
1.blue_sky_420_1280x720.264
2.pedestrian_area_420_720x576.264
3.V30313_B_D-Traffic_AVC_MP_num_ref_frames_6.264
Dropping frames when decoding these three videos，have fixed the bug.

6.MR6_BT_B.264
7.MR8_BT_B.264 
These  two videos belong to extended profile of the spec.
The driver do not support the profile, so yami  also do not support it.

4.V30320_A_D-Traffic_AVC_MP_frame_cropping_2x2.264
5.V30345_B_D-Traffic_AVC_MP_combination.264
Need crop when decoding these two videos. And video itself has a problem.
The yuv file decoded by ffmpeg is totally error, and the yuv file decoded by yamidecode and mv_decoder can be played. So we will check the difference of the two, but now we will keeep it and   then will solve it.

**Comment by xuguangxin** [comment]
@wudping ,could help to check the status of this bug ? Could we close it ?

**Comment by wudping** [comment]
hi @xuguangxin, except the unsupported clips, we have only one clip issue to fix. I am still working on it know, and consult with @lizhong1008  for help. 
please keep it opening.

**Comment by xuguangxin** [comment]
The only clip is cropped one?

**Comment by xuguangxin** [comment]
@wudping

**Comment by wudping** [comment]
I will follow this problem,  @xuguangxin .

**Comment by wudping** [comment]
files MR6_BT_B.264 and MR8_BT_B.264 are extended profile, we don't support them.

files V30320_A_D-Traffic_AVC_MP_frame_cropping_2x2.264 and V30345_B_D-Traffic_AVC_MP_combination.264 contain **crop information**, the patch [714](https://github.com/01org/libyami/pull/714) will support them.

other clips had passed the decoding based on current upstream code.

**Comment by wudping** [comment]
@xuguangxin , yes, it is the crop one.
