### ISSUE TITLE
[media][decode] error message appeared when doing AVC decode test

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#287]
1.Testing environment:
Libva: (master)70b80c0dd2effb4956b208775641f7c68a67a9df
Libva_intel_driver: (master)611d8ea9d75dc026c203e3ebe53b434769d4587c
libyami: (master) 73b2078
ffmpeg: (master) da8b70b810bb2703f976d737af8c68d35716f5ea
2.Reproduce Steps:
  $ ./yamidecode -i /media/avc_vpg/Allegro_Inter_CAVLC_07_5x6_4.6.264 -m 0 -n 50 -f I420
3.Bug detailed description:
 when doing AVC decode test, system showed"libyami error(vaapidecoder_base.cpp, 329): surface pool is not initialized yet"

**Comment by zhongcong** [comment]
There are sps,pps,sei nalu before decoding SLICE nalu(the real codec frame data),  so the first decode unit in h264 is SPS nalu, it return DECODE_SUCCESS but does not setupVA(create display, surface pool and context). And then renderOutputFrames will show out "surface pool is not initialized yet".

**Comment by zhongcong** [comment]
#294 can fix this

**Comment by keqiaox** [comment]
hi all,

 After applied zhongchong's latest patch and retest, the error message does not exists anymore, so this bug can be closed.
