### ISSUE TITLE
[SKL][Regression][decode] decodecapi tool stopped there but without any error message when doing the test

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#288]
1.Testing environment:
Libva: (master)70b80c0dd2effb4956b208775641f7c68a67a9df
Libva_intel_driver: (master)611d8ea9d75dc026c203e3ebe53b434769d4587c
libyami: (master) 73b2078
ffmpeg: (master) da8b70b810bb2703f976d737af8c68d35716f5ea

2.Test command:
1.$ ./decodecapi -i $filename  -m 0 -f I420

3.Bug detailed description
 decodecapi tool stopped there but without any error message when doing the test

**Comment by xuguangxin** [comment]
Hi @andyLiuChina 
Is https://github.com/01org/libyami/pull/289 fixed this issue?

**Comment by keqiaox** [comment]
Hi all, 

 After tested with the latest commit(68d4ea1690c31e61647ec188a8802cc0eb095ee8), not found this issue, so close it.
