### ISSUE TITLE
[HEVC][decode] error message “libyami error(vaapidecoder_base.cpp, 330): surface pool is not initialized yet” appeared when doing HEVC decode test

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#301]
1.Testing environment:
Libva: (master)fdd6ee00c916f530e4d0aa1b250633643999dcf1
Libva_intel_driver: (master)29f4234504fd99299997a3fc2f01393fb77030b7
libyami: (h265dec) 8a003f1
ffmpeg: (master) 4c39892b6741c8553689fb73d5a2f64cd2a3c9eb
2.Test command:
1.$ ./yamidecode -i /media/HEVC/JVT10.0/$filename -m -2 -f I420
3. error message：
libyami error(vaapidecoder_base.cpp, 330): surface pool is not initialized yet
libyami error(vaapidecoder_base.cpp, 330): surface pool is not initialized yet
libyami error(vaapidecoder_base.cpp, 330): surface pool is not initialized yet

**Comment by xuguangxin** [comment]
should fixed by https://github.com/01org/libyami/commit/8d64174072a3611c40bcfd0c63a6fd8457779cd6
but need double check this after we rebased h265dec.

**Comment by keqiaox** [comment]
hi Guangxin,
  Found this issue on h265dec branch.

**Comment by xuguangxin** [comment]
should fixed in 0.3.0 RC. please help to check

**Comment by keqiaox** [comment]
Not found this error message with the latest master branch, so close it.
