### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [01org/libyami#303]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/01org/libyami/blob/a1ed1064697bdb345411bb0e905132fe0a2c05a9/configure.ac#L228 "Configuration checks")?

**Comment by xuguangxin** [comment]
not familiar with this configuration, but we will check this later. thanks for suggestion.
