### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [01org/libyami#304]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [FpsCalc::log](https://github.com/01org/libyami/blob/af3991ab97d95dc5e49f689a121b78567f6b40a0/common/utils.cpp#L202)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [Lock constructor](https://github.com/01org/libyami/blob/3455a93a0830161404149ca9716a4a2fb767a6f6/common/lock.h#L34)

**Comment by xuguangxin** [comment]
Hi elfring:
thanks for comments. But printf and ptreahd_mutex_init only return error in extremely error happened, If this happens, system is unstable. We can't do any thing on this condition.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by xuguangxin** [comment]
are robot?

**Comment by xuguangxin** [comment]
close since elfring is robot

**Comment by elfring** [comment]
A biological system would prefer that strict error detection will become less optional in important software.
Is [the importance of software robustness](https://en.wikipedia.org/w/index.php?title=Robustness_%28computer_science%29 "Making software more robust?") increasing for the affected media library?
