### ISSUE TITLE
[Decode][vp9] 3 clips (test suits2) decoding failed 

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#307]
1.Testing environment:
Libva: (v1.6-branch)f7fbdccc65147b2a4b18db9855217a40b56f43aa
Libva_intel_driver: (v1.6-branch)bae95b257043c8376b222cba2fc19d639c6c73c6
libyami: (master) a4cb390
ffmpeg: (master) 61009a709c76ec2a8529c0fcf15057d82bed6454
cmrt:(master) def7965ab7ed16f5f0dfed61107687209b430cd4
intel-hybrid-driver:(master) d4089062024183edf54278ec9080667639a3d6a8

2.Test command:
./yamidecode -i /media/test_suits2/$filename -m -2

3.Failed cases and error message related
 
 Stress_VP9_1920x1080_250_extra_stress_1.1.vp9  ------ Aborted (core dumped)
 Syntax_VP9_16384x240_201_extra_tiles_1.1.vp9  ------ Aborted (core dumped)
 Syntax_VP9_4320x240_201_extra_tiles_1.1.vp9   ------  Aborted (core dumped)

**Comment by zhongcong** [comment]
these 3 decoding failed clips are filed in #257 , so this issue can be closed.

**Comment by xuguangxin** [comment]
@keqiaox ,could we close this as cong suggested

**Comment by keqiaox** [comment]
It's OK to me, so close this bug and track #257 for this issue.
