### ISSUE TITLE
[Decode][vp9] 19 clips (test suits3) decoding failed with error message "fail to init input stream"

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#308]
1.Testing environment:
Libva: (v1.6-branch)f7fbdccc65147b2a4b18db9855217a40b56f43aa
Libva_intel_driver: (v1.6-branch)bae95b257043c8376b222cba2fc19d639c6c73c6
libyami: (master) a4cb390
ffmpeg: (master) 61009a709c76ec2a8529c0fcf15057d82bed6454
cmrt:(master) def7965ab7ed16f5f0dfed61107687209b430cd4
intel-hybrid-driver:(master) d4089062024183edf54278ec9080667639a3d6a8

2.Test command:
./yamidecode -i /media/test_suits3/$filename -m -2

3.Failed cases:
g2_decoder_case_15024.vp9.webm 
g2_decoder_case_15025.vp9.webm 
g2_decoder_case_15708.vp9.webm 
g2_decoder_case_15856.vp9.webm 
g2_decoder_case_15858.vp9.webm 
g2_decoder_case_15897.vp9.webm 
g2_decoder_case_15898.vp9.webm 
g2_decoder_case_15910.vp9.webm 
g2_decoder_case_15917.vp9.webm 
g2_decoder_case_16194.vp9.webm 
g2_decoder_case_16195.vp9.webm 
g2_decoder_case_16196.vp9.webm 
g2_decoder_case_16517.vp9.webm 
Stress_VP9_1920x1080_250_extra_stress_1.1.vp9.webm 
vp9_seg_bipred_sf_LAST_ALT_GOLD_Riverbed_1024x1024_64x64_584x808.vp9.webM 

4.error message
fail to init input stream

**Comment by keqiaox** [comment]
Remove the unsupported bitstreams:
Syntax_VP9_16384x240_201_extra_tiles_1.1.vp9.webm
Syntax_VP9_4320x240_201_extra_tiles_1.1.vp9.webm
vp9_max_tile_row2_col6_CrowdRun_8192x2160.vp9.webM
vp9_seg_hybridpred_sf_GOLD_LAST_ALT_INTRA_beans_8192x64_8184x56_8192x48.vp9.webM

**Comment by ghost** [comment]
1.0.0 RC2 test update:
Those case all are odd resolution case, remove it from our test case.
