### ISSUE TITLE
Need a way to get libyami version

### ISSUE THREAD

**Issue by jsorg71** [01org/libyami#318]
libva has a good method for getting the version both at compile time and run time.
va_version.h for compile time and vaInitialize for run time.
Can we add similar version info for libyami?

**Comment by xuguangxin** [comment]
OK, we will add this in next release.thanks for report

**Comment by xuguangxin** [comment]
Hi jsorg:
I think this fixed in apache branch right?

**Comment by jsorg71** [comment]
It looks like we have
#define YAMI_API_MAJOR_VERSION    0
#define YAMI_API_MINOR_VERSION    2
#define YAMI_API_MICRO_VERSION    0
for compile time and
void yamiGetApiVersion(uint32_t *apiVersion);
for run time.

I did not test but it looks to be fixed.

Jay

**Comment by xuguangxin** [comment]
Great! Do not hesitate to open a issue if you have.
thanks
