### ISSUE TITLE
[Decode][H265]The MD5 values are not the same as the reference data when doing H265 decode test by using test suits4 clips

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#320]
1.Testing environment:
  Libva: (v1.6-branch) 613eb962b45fbbd1526d751e88e0d8897af6c0e0
  Libva_intel_driver: (v1.6-branch) 35858c69166b845c59ca32e19a3dbb0b758df209
  Cmrt: (master)393ba334aa50aac31da64c2f9855cb66e43b067d
  intel-hybrid-driver(master) 37f6af6abf20f267efdacd4ccf0f82f351fa28db
  libyami: (master) 183e322d3bd96bb57d451cebca3bcc2b499ba4bc
  ffmpeg: (master) 61009a709c76ec2a8529c0fcf15057d82bed6454
2.Test command:
 $ ./yamidecode -i /media/HEVC/test_suits4/$filename -m -2 -f I420
3.failed cases:
 94 cases failed.

**Comment by ghost** [comment]
We already have a bug on Jira to track this issue. So close this one.
