### ISSUE TITLE
registry factory is not work in static link mode.

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#330]
1. configure yami with this configuration: ./configure --with-pic --enable-static --disable-shared
2. run "yamidecode -i xxx.264"
you will see 
"libyami error(vaapidecoder_host.cpp, 55): Failed to create decoder for mimeType: 'video/h264'"
seem h264 decoder did not registered.

after search the web, I find it maybe related to static member's init problem. c++ do not guarantee the static member's init order. So maybe VaapiEncoderH264::s_registered init before Factory<T>::m_creators.

Hi @uartie : do you have better way to fix this? Else we may need fallback to old way.

**Comment by uartie** [comment]
I will look into this... it should be possible to make it work.

**Comment by xuguangxin** [comment]
Great! Thanks very much.

**Comment by uartie** [comment]
xuguangxin, can you verify that this fixes all the tests and examples?

**Comment by uartie** [comment]
#333 should fix this now.
