### ISSUE TITLE
[HEVC][decode] the MD5 values are not the same as the reference data when using the ffmpeg contents

### ISSUE THREAD

**Issue by keqiaox** [01org/libyami#340]
1.Testing environment:
Libva: (master) d3b24b76dfde4daef9d463743971c7522a307092
Libva_intel_driver: (master) 4640d06a8ccb0a12e91bbd00cc3e2423d17ee243
libyami: (master) af50400
ffmpeg: (master) 74e4948235bc8f8946eeca20525258bbf383f75d
Cmrt: (master)393ba334aa50aac31da64c2f9855cb66e43b067d
intel-hybrid-driver(master) 37f6af6abf20f267efdacd4ccf0f82f351fa28db

2.Test command:
$ ./yamidecode -i ./$filename -m -2 -f I420

3.Failed cases:
1---BUMPING_A_ericsson_1.bit
2---CONFWIN_A_Sony_1.bit
3---TSKIP_A_MS_2.bit
4---NoOutPrior_B_Qualcomm_1.bit
5---OPFLAG_B_Qualcomm_1.bit
6---OPFLAG_C_Qualcomm_1.bit
7---SLIST_D_Sony_9.bit
8---EXT_A_ericsson_3.bit

**Comment by xuguangxin** [comment]
@wudping ,Please help to check this.

**Comment by wudping** [comment]
okay, @xuguangxin .

**Comment by wudping** [comment]
hi @xuguangxin , we have only one clip issue except the unsupported; That clip issue is fixed by 

> commit 35e5ecdb1c5c280dfe865f36284995c7db436009

so it can be closed. 
thanks.

**Comment by ghost** [comment]
I will check this issue during RC2 test.

**Comment by ghost** [comment]
@wudping @xuguangxin  1.0.0 RC2 test still 6 fail case:

decode_hevc_ffmpeg/BUMPING_A_ericsson_1.bit  FAIL
decode_hevc_ffmpeg/CONFWIN_A_Sony_1.bit  FAIL
decode_hevc_ffmpeg/NoOutPrior_B_Qualcomm_1.bit  FAIL
decode_hevc_ffmpeg/OPFLAG_B_Qualcomm_1.bit  FAIL
decode_hevc_ffmpeg/OPFLAG_C_Qualcomm_1.bit f FAIL
decode_hevc_ffmpeg/TSKIP_A_MS_2.bit  FAIL

**Comment by ghost** [comment]
Double checked with dongping, md5 same with ffmpeg, and remove CONFWIN_A_Sony_1.bit case for not support crop.
