### ISSUE TITLE
v4l2_wrapper.h include path issue

### ISSUE THREAD

**Issue by halleyzhao** [01org/libyami#349]
VideoCommonDefs is installed to "libyami_decoder/VideoCommonDefs.h"; different from it in original source code.

patch is too small, please correct it in your convenient way.

diff --git a/v4l2/v4l2_wrapper.h b/v4l2/v4l2_wrapper.h
index ac7eaa5..749fef8 100644
--- a/v4l2/v4l2_wrapper.h
+++ b/v4l2/v4l2_wrapper.h
@@ -27,7 +27,7 @@
 #else
 #include <EGL/egl.h>
 #endif
-#include "interface/VideoCommonDefs.h"
+#include "VideoCommonDefs.h"
 
 #ifndef v4l2_wrapper_h
 #define v4l2_wrapper_h

**Comment by xuguangxin** [comment]
+1 for patch

**Comment by xuguangxin** [comment]
close this since merged it as 1dddbab5bd05a09f01f7e833d8937ffa270e2fd1
thanks Halley.
