### ISSUE TITLE
signed/unsigned comparison warning issue in libyami

### ISSUE THREAD

**Issue by halleyzhao** [01org/libyami#350]
there are still many warning on signed/unsigned comparison issue during yami build.
please help to correct them.

the warning is treated as error in my build server (local build and cross-build use the same toolchain).
though, I had tried to work around them on my side; it's better to re-evaluate  these issues (may start from the variable definition).

thanks.

**Comment by xuguangxin** [comment]
We tried this before. but it's too huge efforts. Especially some thing from codec parser. So we just ignore this on https://github.com/01org/libyami/blob/master/configure.ac#L287. Why you still see this error.Is this fix not work for you?

**Comment by halleyzhao** [comment]
because I work on a build server which enables [-Werror=sign-compare].
the configuration of the server is out of my scope.

utils.cpp: In function 'uint32_t YamiMediaCodec::guessFourcc(const char*)':
utils.cpp:49:29: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

**Comment by xuguangxin** [comment]
ok, we will fix this

**Comment by seanvk** [comment]
I think this should fall under a bigger issue that states that we need to cleanup all warnings.  This is critical for upstreaming to distributions (gentoo, debian, fedora)

**Comment by xuguangxin** [comment]
yes. @wudping is work on this. and the patch is under review.

**Comment by xuguangxin** [comment]
this fix in apache branch. so close it
