### ISSUE TITLE
h264 decoder issue exposed during build

### ISSUE THREAD

**Issue by halleyzhao** [01org/libyami#351]
Ubuntu 15.10 + braswell
it seems to be a real bug.

vaapidecoder_h264.cpp: In member function 'void YamiMediaCodec::VaapiDecoderH264::initPicturePOC0(const PicturePtr&, const SliceHeaderPtr&)':
vaapidecoder_h264.cpp:360:33: error: comparison of constant '2' with boolean expression is always false [-Werror=bool-compare]
             (m_prevPicStructure == VAAPI_PICTURE_STRUCTURE_BOTTOM_FIELD ?
                                 ^
mv -f .deps/libyami_decoder_la-vaapidecoder_host.Tpo .deps/libyami_decoder_la-vaapidecoder_host.Plo

**Comment by xuguangxin** [comment]
Hi @halleyzhao : 
Did you use a old version of libyami? It should be fixed by daniel's patch https://github.com/01org/libyami/commit/37958b645953498c749c6d85be56eb6ccdf7e048

**Comment by halleyzhao** [comment]
I uses the release branch.

maybe I should use master instead.

**Comment by xuguangxin** [comment]
yes. this because we do not release new version yet.

**Comment by xuguangxin** [comment]
close this since it's not a problem
