### ISSUE TITLE
"v4l2decode -m 0" fails in some build configuration

### ISSUE THREAD

**Issue by halleyzhao** [01org/libyami#353]
halley@halley-braswell:~/yami/libyami/tests$ ./v4l2decode -m 0 -i /home/halley/video-contents/output.h264 
input file: /home/halley/video-contents/output.h264, renderMode: 0
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965
libyami error(vaapiutils.h, 62): vaInitialize: operation failed
libyami error(vaapidecoder_base.cpp, 382): failed to create display
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965
libyami error(vaapiutils.h, 62): vaInitialize: operation failed
libyami error(vaapidecoder_base.cpp, 382): failed to create display
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965
libyami error(vaapiutils.h, 62): vaInitialize: operation failed
libyami error(vaapidecoder_base.cpp, 382): failed to create display
^C
halley@halley-braswell:~/yami/libyami/tests$ vainfo
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /home/halley/yami_install/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.38 (libva 1.6.2.pre1)
vainfo: Driver version: Intel i965 driver for Intel(R) CherryView - 1.6.2.pre1 (1.6.1-52-g589b7a8)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD

**Comment by halleyzhao** [comment]
here is my build configuration:

*======================current configuration=============================
* VAAPI_PREFIX:               /home/halley/yami_install/vaapi
* LIBYAMI_PREFIX:             /home/halley/yami_install/libyami
* LD_LIBRARY_PATH:            /home/halley/yami_install/vaapi/lib/:/home/halley/yami_install/libyami/lib/:
* PATH:                       /home/halley/yami_install/vaapi/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
*=========================================================================
* vaapi:      git clean -dxf && ./autogen.sh --prefix=$VAAPI_PREFIX --disable-x11 --disable-glx --disable-egl --disable-wayland && make -j8 && make install
* ffmpeg:     git clean -dxf && ./configure --prefix=$VAAPI_PREFIX && make -j8 && make install
* libyami:    git clean -dxf && ./autogen.sh --prefix=$LIBYAMI_PREFIX --enable-tests --enable-x11=no --enable-v4l2=yes --disable-h265dec && make -j8 && make install

**Comment by xuguangxin** [comment]
this because we default open x on VaapiDisplay. We will refact this. and send patch for this every soon.

**Comment by halleyzhao** [comment]
seems my mistake. maybe I used system libva instead. now it works for me:

[yami_make] halley@halley-braswell:~/yami/libyami/tests$ ./v4l2decode -m 0 -i ~/video-contents/output.h264 
input file: /home/halley/video-contents/output.h264, renderMode: 0
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /home/halley/yami_install/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
rendered frame count: 850 in 1474 ms; fps=576.66
decode done

**Comment by halleyzhao** [comment]
in order to make sure i'm in the correct env of yami build, I added the following to the previous setup_env scripts:

if test -z "$PS1_OLD"; then
    export PS1_OLD=$PS1
fi

export PS1="\[\033[0;31m\][yami_make]\[\033[0m\] $PS1_OLD"

**Comment by halleyzhao** [comment]
又像是个随机的问题了，vainfo去查找了正确的i965 driver;但是yamidecode/v4l2deco没有相关的log信息：

[yami_make] halley@halley-braswell:~/yami$ v4l2decode -m 0 -i /home/halley/video-contents/output.h264 
input file: /home/halley/video-contents/output.h264, renderMode: 0
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965
libyami error(vaapiutils.h, 62): vaInitialize: operation failed
libyami error(vaapidecoder_base.cpp, 382): failed to create display
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965
libyami error(vaapiutils.h, 62): vaInitialize: operation failed
libyami error(vaapidecoder_base.cpp, 382): failed to create display
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 1
libva error: va_getDriverName() failed with operation failed,driver_name=i965
libyami error(vaapiutils.h, 62): vaInitialize: operation failed
libyami error(vaapidecoder_base.cpp, 382): failed to create display

^C
[yami_make] halley@halley-braswell:~/yami$ vainfo
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /home/halley/yami_install/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.38 (libva 1.6.2.pre1)
vainfo: Driver version: Intel i965 driver for Intel(R) CherryView - 1.6.2.pre1 (1.6.1-52-g589b7a8)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice

**Comment by xuguangxin** [comment]
@clearlylin , please help to check. thanks.

**Comment by clearlylin** [comment]
@xuguangxin 
building and running in my computer, the problem can not reappear.

**Comment by halleyzhao** [comment]
it is reproduced when current user is not in "video" group.
while vainfo is ok even when current user is not in "video" group.

so, we still need investigate it futhure.

**Comment by xuguangxin** [comment]
@clearlylin, please help to check this.

**Comment by xuguangxin** [comment]
@clearlylin , any update on this?

**Comment by clearlylin** [comment]
@xuguangxin , no

**Comment by xuguangxin** [comment]
Hi @halleyzhao :
you still have this problem?

**Comment by xuguangxin** [comment]
Hi @halleyzhao 
close this first, If you still have this problem. Please reopen it.
thanks
