### ISSUE TITLE
compiler error 

### ISSUE THREAD

**Issue by chivakker** [01org/libyami#375]
compiler error with gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)

when configuring with --enable-v4l2-glx the following linking exception occurs

g++ -DHAVE_CONFIG_H -I. -I.. -I.. -I.. -I../interface -I/home/dcharles/include      -g -O2 -Wno-unused-function -Wno-sign-compare -Wno-cpp -Wall -Werror -MT v4l2decode.o -MD -MP -MF .deps/v4l2decode.Tpo -c -o v4l2decode.o v4l2decode.cpp
v4l2decode.cpp:130:20: error: ‘typeStrDmaBuf’ defined but not used [-Werror=unused-variable]
 static const char* typeStrDmaBuf = "dma-buf";
                    ^
v4l2decode.cpp:131:20: error: ‘typeStrRawData’ defined but not used [-Werror=unused-variable]
 static const char* typeStrRawData = "raw-data";
                    ^
v4l2decode.cpp:133:20: error: ‘memoryTypeStr’ defined but not used [-Werror=unused-variable]
 static const char* memoryTypeStr = typeStrDrmName;
                    ^
cc1plus: all warnings being treated as errors

**Comment by xuguangxin** [comment]
fixed by #374 
thanks Daniel
