### ISSUE TITLE
CXXFLAGS and CFLAGS should not be specified in configure.ac or Makefile.am

### ISSUE THREAD

**Issue by uartie** [01org/libyami#382]
Commit 7e2556efc8223b0f0289894364012e47cb6de548 moved these *user* flags out of the autogen.sh script, which is good.  However, although they don't belong in autogen.sh, they don't belong in configure.ac or any of the Makefile.am files, either.

As far as I can tell, it looks like the project is trying to globally enforce various compiler/preprocessor flags (e.g. -Wall -Werror), which is great.  However, specifying that policy within the *user* flags is not the correct way to do it.  The problem is that if I, as the user, want to specify some additional CXXFLAGS to configure, then the ones in configure.ac get overridden by my local CXXFLAGS setting.  I don't think this is the intention that the project is going for.  Instead, we should be enforcing these flags via the AM_ variants.

See https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html for more details on the correct way to do this.

**Comment by seanvk** [comment]
We need to remove this and use AM_flags in Makefile.am.  
+1

**Comment by uartie** [comment]
As a note, preprocessor/compiler flags specified in AM_C[XX]FLAGS can be negated by their user variable counterparts.  For example, AM_C[XX]FLAGS="-Wall -Werror" can be negated by the user with C[XX]FLAGS="-Wno-all -Wno-error".  I think it's better since it's more explicit and it won't silently override other project-configured compiler/preprocessor flags.  Also consider that if I want to debug the library, I can just set C[XX]FLAGS="-O0" in my environment (or command line) and would still get the project-wide C[XX]FLAGS if they are correctly configured within the AM_C[XX]FLAGS.

C[XX]FLAGS meaning either CFLAGS or CXXFLAGS, of course.
