### ISSUE TITLE
Clean up Warnings in all build configurations

### ISSUE THREAD

**Issue by seanvk** [01org/libyami#385]
It will point to errors in build configurations and the code as well.

**Comment by xuguangxin** [comment]
yes. we have treat all warning as error. in 
https://github.com/01org/libyami/blob/master/configure.ac#L299
But the difficult thing is we have too many --enable-xxx build options. some are exclusive. Hard test it all.

**Comment by xuguangxin** [comment]
Hi @seanvk 
We already treat warning as error in compile flag. Do you think it's ok to close this

**Comment by xuguangxin** [comment]
Hi @seanvk :
Temporarily close this. If you think this still a issue, please report it.
thanks.
