### ISSUE TITLE
Consider creation of more simplified functional test code

### ISSUE THREAD

**Issue by seanvk** [01org/libyami#386]
Yamidecode is not a good choice for API validation and we need both single purpose API Validation and a good clean reference for API implementation.

**Comment by xuguangxin** [comment]
for decode we have simple API usage demo application https://github.com/xuguangxin/libyami/blob/master/examples/simpleplayer.cpp.
less than 200 line of code. demo all decode apis

**Comment by xuguangxin** [comment]
mentioned this in readme https://github.com/01org/libyami/pull/402/files
