### ISSUE TITLE
omxh264enc need to support more parameter 

### ISSUE THREAD

**Issue by zliu50x** [01org/libyami#39]
omxh264enc should add more parameter control, please reference the gstreamer vaapi's parameter
"vaapiencode_h264 rate-control=cqp keyframe-period=30 max-bframes=2 init-qp=28 cabac=true"
gstreamer vaapi parameter information:
1. rate-control : Rate control mode
    flags: readable, writable
    Enum "GstVaapiRateControlH264" Default: 1, "cqp"
        (1): cqp              - Constant QP
        (2): cbr              - Constant bitrate
        (4): vbr              - Variable bitrate
        (5): vbr_constrained  - Variable bitrate - Constrained
2. keyframe-period  : Maximal distance between two keyframes (0: auto-calculate)
        flags: readable, writable
        Unsigned Integer. Range: 1 - 300 Default: 30
3. max-bframes : Number of B-frames between I and P
        flags: readable, writable
        Unsigned Integer. Range: 0 - 10 Default: 0
4. init-qp : Initial quantizer value
        flags: readable, writable
           Unsigned Integer. Range: 1 - 51 Default: 26
5. cabac : Enable CABAC entropy coding mode
        flags: readable, writable
        Boolean. Default: false

**Comment by xuguangxin** [comment]
we will note support gstreamer omx plugins. so close it
