### ISSUE TITLE
The pre-commit hook does not follow coding-style

### ISSUE THREAD

**Issue by uartie** [01org/libyami#390]
https://github.com/01org/libyami/wiki/Coding-Style states that libyami uses the Webkit coding style.  However, the `pre-commit` hook does a very poor job at formatting the code according to the Webkit coding-style guidelines.  We should either fix the pre-commit hook to follow the coding style or stop asking users to use the hook and remove it from the source tree.

**Comment by xuguangxin** [comment]
Seems  the hook do bad things for c++ file. and we did not find a right tool for them. Remove it is good
