### ISSUE TITLE
Enabling capi and tests should not skip yami[decode|encode|vpp|transcode] compilation

### ISSUE THREAD

**Issue by uartie** [01org/libyami#394]
`tests/Makefile.am` has rules to skip `yami[decode|encode|vpp|transcode]` compilation if `ENABLE_CAPI` is defined (i.e. `--enable-capi --enable-tests`).

I'm not sure if there is any technical reason why we can't compile both sets of programs.  Let's not skip the `yami[decode|encode|vpp|transcode]` compilation due to --enable-capi.

**Comment by xuguangxin** [comment]
It's history reason. We have different memory layout for capi and c++ api. Maybe we need change it in feature. to support capi and c++ api at same time.

**Comment by ghost** [comment]
RC1 test OK.
