### ISSUE TITLE
Compile fails with VA-API version 0.36 (libva 1.4.1)

### ISSUE THREAD

**Issue by uartie** [01org/libyami#397]
The configure.ac defines the minimum libva version requirement as 0.36.  The following libyami options fail to compile against libva 0.36:

1.  --enable-vp9dec
vaapidecoder_vp9.h:29:27: fatal error: va/va_dec_vp9.h: No such file or directory

2. --enable-h265dec (default is yes, btw)
vaapidecoder_h265.h:124:24: error: 'VAPictureHEVC' has not been declared

3. --enable-jpegenc
vaapiencoder_jpeg.h:29:28: fatal error: va/va_enc_jpeg.h: No such file or directory

4. --enable-h265enc
vaapiencoder_hevc.h:36:28: fatal error: va/va_enc_hevc.h: No such file or directory

5. --disable-h265enc
vaapiencoder_base.cpp:392:31: error: 'VAProfileHEVCMain' was not declared in this scope
vaapiencoder_base.cpp:393:33: error: 'VAProfileHEVCMain10' was not declared in this scope

The configure.ac ought to handle these scenarios properly.  For example, either require a newer minimum libva version or warn the user and auto disable them or emit an error during configure.  

Currently, the workaround for the user is to disable the unsupported codecs during the configure phase (h265dec has to be explicit, the others can be implicit).  However this does not work for option 4 since we end up with the failure in option 5.

**Comment by xuguangxin** [comment]
LinHai  already submit a patch check   headers https://github.com/clearlylin/libyami/commit/988daf2f4f4267952eeecb3405a2efbf5f808365
but it still under review..
and we should fix item 5 late

**Comment by clearlylin** [comment]
@xuguangxin 
[988daf2](https://github.com/clearlylin/libyami/commit/988daf2f4f4267952eeecb3405a2efbf5f808365) can not solve the problem. if vaapi/header install to directory of system, that way is ok. if the installation directory is custom directory, that is useless.

**Comment by xuguangxin** [comment]
Hi @wudping 
Do we still have this issue?

**Comment by xuguangxin** [comment]
fixed by https://github.com/01org/libyami/pull/540
