### ISSUE TITLE
why is the 'wa'  so high?

### ISSUE THREAD

**Issue by jeason2014** [01org/libyami#398]
Hi,
My Linux kernel is 4.2.First, I ran 20 yamiencode on skl platform to test encode performance,and then I ran 'top' to know CPU cost:
%Cpu0  : 17.4 us, 10.9 sy,  0.0 ni,  2.2 id, 68.5 wa,  0.0 hi,  1.1 si,  0.0 st
%Cpu1  : 18.0 us, 14.0 sy,  0.0 ni,  0.0 id, 68.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : 13.3 us, 15.3 sy,  0.0 ni,  0.0 id, 71.4 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 19.2 us, 13.1 sy,  0.0 ni,  1.0 id, 66.7 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  : 11.0 us, 18.0 sy,  0.0 ni,  0.0 id, 71.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  : 13.1 us, 14.1 sy,  0.0 ni,  1.0 id, 71.7 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  : 13.7 us, 16.7 sy,  0.0 ni,  0.0 id, 69.6 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  : 15.7 us, 10.8 sy,  0.0 ni,  2.9 id, 70.6 wa,  0.0 hi,  0.0 si,  0.0 st
I have modified the encode.cpp to avoid disk IO cost(read all yuv data to memory before encode,and not write encode data to disk),but the 'wa' is still so high.
Do you know the reason? thanks.

**Comment by xuguangxin** [comment]
you should use yamitranscode. yamiencode will map and copy decoded surface to encode input and yamitranscode will not. But current yamitranscode do not accept encode param. when it supports,  we will remove yamiencode.
here is yami transocode  command line
"yamitranscode  -i  640x480.264 -o 640x480_output.264"

**Comment by jeason2014** [comment]
Hi xu,
you mean the high 'wa' is caused by memcpy? is it in this function:SurfacePtr VaapiEncoderBase::createSurface(VideoFrameRawData* frame)?

in addition,what's the difference between new memory 、surface memory and encode intput memory?

thanks!

**Comment by xuguangxin** [comment]
Hi Jeason:
Yes. in createSurface(VideoFrameRawData* frame). We will remove this in future.

There are two type of memory in this context
tiled memory: mainly for gpu. cpu write is moderate slow. cpu read is extremely slow. CPU will disable cache for this memory.
untiled (linear) memory: mallocaed memory.
gpu (decode, encode, vpp) always use tiled memory. 
In YamiEncode case it will copy decoded memory to encode input. there are all tiled. So it extremely slow. yamitransocde will use vpp function. do scale or memory copy thing. cpu do not handle yuv data.

**Comment by jeason2014** [comment]
Hi xu,
Thank you so much,I got it.
But,I will be encode the yuv data which from PCIe ,so  cpu have to write tiled memory. 
Do you have any idea?

**Comment by jeason2014** [comment]
you mean the high 'wa' is caused by memcpy? is it in this 
function:SurfacePtr VaapiEncoderBase::createSurface(VideoFrameRawData* 
frame)?

in addition,what's the difference between new memory 、surface memory and 
encode intput memory?

thanks!

-----------------------------------------
苏州科达通信技术发展有限公司上海分公司
Add:上海市虹梅路2071号远中产业园四期1号楼4楼（201103）
Tel：7872
Email：fanchao@kedacom.com
-----------------------------------------



Xu Guangxin <notifications@github.com> 
2015-12-21 11:39
请答复 给
01org/libyami 
<reply@reply.github.com>


收件人
01org/libyami <libyami@noreply.github.com>
抄送
jeason2014 <fanchao@kedacom.com>
主题
Re: [libyami] why is the 'wa'  so high? (#398)






you should use yamitranscode. yamiencode will map and copy decoded surface 
to encode input and yamitranscode will not. But current yamitranscode do 
not accept encode param. when it supports, we will remove yamiencode.
here is yami transocode command line
"yamitranscode -i 640x480.264 -o 640x480_output.264"
―

**Comment by xuguangxin** [comment]
Hi Jeason:
write is ok, since we have [write combine](https://en.wikipedia.org/wiki/Write_combining).But you need avoid read. 
why you need copy from PCIe. do you use nv card?

**Comment by xuguangxin** [comment]
Yes. cause by read untiled memory. It's no cache.

**Comment by jeason2014** [comment]
Hi xu,
I don't use nv card, the yuv data from other chips by Pcie.
Now,I have two problems:
1、the yuv before encode ,which is from other chips by pcie,
2、the yuv after decode, which be sent to other chips by pcie.
So, is there a way to avoid memcpy between tiled and untiled?
if the pcie memory  is non-cache and continuous physical address, it can be used to codec directly?

thanks!

**Comment by xuguangxin** [comment]
seems no way to avoid copy if your memory in pcie.
for encoder,  you need copy the yuv to encode input surface. it not slow since it have write combine.
for decoder, you can create tiled memory like [this](https://github.com/thuutin/hardware_intel_common_libmix/blob/master/videodecoder/VideoDecoderBase.cpp#L899) and use yami's vpp function to copy tiled memory to untiled. then copy data from untiled to pcie.

**Comment by jeason2014** [comment]
Hi xu,
thanks! I will be try.
In addition,I ran "./yamidecode -i 4k2k.264 -m -1",the 'wa' is high too.
it's caused by memcpy between tiled and untiled?

**Comment by xuguangxin** [comment]
Hi Jeanson:
I tried a 4kx2k video on my HSW. the wa is about 11. 
%Cpu(s):  0.7 us,  5.4 sy,  0.0 ni, 82.9 id, 11.0 wa,  0.0 hi,  0.0 si,  0.0 st

So did you use a ssd ?

**Comment by xuguangxin** [comment]
Hi Jeason:
Do you have any feedback about this?

**Comment by jeason2014** [comment]
Hi xu:
the ssd is Solid State Disk,right?
I don't use ssd.
root:/home/media# lsscsi
[0:0:0:0]    disk    ATA      WDC WD20PURX-64P 0A80  /dev/sda

**Comment by xuguangxin** [comment]
Hi Jeanson:
Maybe this the reason. you can try to put the encoder input and output to a ram directory.such as /tmp.

**Comment by xuguangxin** [comment]
Hi Jeason:
any  update on this?

**Comment by xuguangxin** [comment]
Hi Jeason:
I will close this, please reopen it if you still have problem. thanks
