### ISSUE TITLE
pc file for capi

### ISSUE THREAD

**Issue by BtbN** [01org/libyami#399]
The capi library is missing a pkgconfig pc file, which makes it realy hard to use it from other projects.

**Comment by clearlylin** [comment]
will merge libyami_capi.so to libyami.so.

**Comment by xuguangxin** [comment]
Hi BtbN:
Thanks for patch. But we moveforward to merge all libyamixxx.so to libyami.so. It should fix the problem, right?

**Comment by BtbN** [comment]
Yep, sounds like an even better solution to me. Thanks
