### ISSUE TITLE
transcode will get error bitstream if we assign a bit rate

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#415]
"DISPLAY=:0   tests/.libs/yamitranscode  -i ~/projects/bits/cin.264 -o  1280x720.264 -N 1500  -b 2500"
it will print out "Unrepairable overflow", the bit stream is not correct.
but "DISPLAY=:0   tests/.libs/yamitranscode  -i ~/projects/bits/cin.264 -o  1280x720.264 -N 1500" do not have this problem

**Comment by lizhong1008** [comment]
How about "DISPLAY=:0 tests/.libs/yamitranscode -i ~/projects/bits/cin.264 -o 1280x720.264 -N 1500 --rcmode CBR -b 2500" and "DISPLAY=:0 tests/.libs/yamitranscode -i ~/projects/bits/cin.264 -o 1280x720.264 -N 1500 --rcmode CBR -b 5000"?

**Comment by xuguangxin** [comment]
I tried this in command line in yamiencode and yamitranscode. It print error too.

**Comment by wudping** [comment]
print out error CMD:
yamitranscode -i ../cin.264  -o dd_1280x720.264 -N 1500 --rcmode CBR -b 5000 1>dd1.txt

will not print out error CMD:
yamitranscode -i ../cin.264  -o dd_1280x720.264 -N 1500 --rcmode CBR -b 1000 1>dd1.txt

It seems like that the bitrate is too large for hardware to malloc a buffer for encoder.

**Comment by wudping** [comment]
I used an upper limit and a bottom boundary as the bitrate in following commands. It printed  waring "unrepairable overflow", but the decoded H264 files are correct.
yamitranscode -i ../cin.264 -o dd_1280x720.264 -N 1500 --rcmode CBR -b 5000 1>dd1.txt
yamitranscode -i ../cin.264 -o dd_1280x720.264 -N 1500 --rcmode CBR -b 1 1>dd1.txt

The following command is ok.
yamitranscode -i ../cin.264 -o dd_1280x720.264 -N 1500 --rcmode CBR -b 1000 1>dd1.txt

**Comment by xuguangxin** [comment]
ok, we should close this
