### ISSUE TITLE
Memory Leak in JPEG encoder

### ISSUE THREAD

**Issue by uartie** [01org/libyami#430]
The packed_header_buffer at
https://github.com/01org/libyami/blob/0412d64f1c8468a87eff5c88c45d7fc061ee5e3a/encoder/vaapiencoder_jpeg.cpp#L458 is not free'd after it has been added to the picture and results in a memory leak.  The picture passes this buffer to vaCreateBuffer() where it gets copied and therefore should be deleted afterwards by the encoder.

**Comment by xuguangxin** [comment]
Hi @uartie 
Is this fixed in Apache branch?

**Comment by uartie** [comment]
yes, this is fixed in apache branch.
