### ISSUE TITLE
[REQUEST] libyami decoders and encoders for Google's MediaCodec API (on Android OS)

### ISSUE THREAD

**Issue by Hedda** [01org/libyami#437]
Please consider porting each libyami decoder and encoder to Google's MediaCodec API (on Android).

Google's MediaCodec API is the somewhat newish de facto standard Android class to allow software applications to access low-level media codecs, i.e. encoder/decoder components.

Note that while this MediaCodec API used to be poorly documented, since Android 6.0 Marshmallow (API 23) the official documentation is actually quite detailed and very useful.

http://developer.android.com/reference/android/media/MediaCodec.html

https://software.intel.com/en-us/android/articles/android-hardware-codec-mediacodec

http://bigflake.com/mediacodec/

http://developer.qualcomm.com/blog/mediacodec-and-openmax-feature-based-video-codec-api-comparison

**Comment by seanvk** [comment]
Currently limited support is planned for Android environments.

**Comment by Hedda** [comment]
@seanvk Cool, but please consider planning to have the implementation use Google's MediaCodec API as standard (and default) and not some other custom integration on Android.

**Comment by Hedda** [comment]
Any change in priority and updates on this now that both MediaCodec API and Android apps also runs in Chromium OS on Google Chromebooks as well?

Looks like Google is slowly merging the Android OS and Chromium OS platforms, or at least making them share some APIs, like the MediaCodec API.

If there was libyami decoders and encoders for the MediaCodec API then those could be used on both Android OS and latest version of Chromium OS.

**Comment by xuguangxin** [comment]
Hi @Hedda ,
Due to our resource, we still have limited support on android. Maybe you can try it your self,MeidaCodec’s interface is similar to yami. I guess you can get a bare bone in less than 1K source code, 2 k source should enough for a decent MediaCodec implementation for yami.

**Comment by Hedda** [comment]
Should this ticket not still be opened if on the roadmap but just not prioritized?
