### ISSUE TITLE
Break out utilities into separate project

### ISSUE THREAD

**Issue by seanvk** [01org/libyami#438]
@chivakker We need to have a separate project for the libyami utilities.  Should be straightforward.  I'll create a repo.

Sean

**Comment by seanvk** [comment]
libyami-utils?

**Comment by chivakker** [comment]
I am okay with the name.

**Comment by uartie** [comment]
The name seems reasonable to me.

**Comment by seanvk** [comment]
Done.

https://github.com/01org/libyami-utils

**Comment by xuguangxin** [comment]
close this since it done
