### ISSUE TITLE
Don't abort in encoder if fourcc not supported/handled

### ISSUE THREAD

**Issue by uartie** [01org/libyami#439]
If the encoder doesn't support a particular fourcc in createNewSurface() then we should not be asserting and forcing the client program to terminate.  Instead we should log an error and return an uninitialized SurfacePtr so the encoder can gracefully propagate the error state back to the client.  This will allow the client program to decide how to recover if needed.

https://github.com/01org/libyami/blob/0412d64f1c8468a87eff5c88c45d7fc061ee5e3a/encoder/vaapiencoder_base.cpp#L266

In general, ASSERT should only be used in rare cases... especially when it's a client library.

**Comment by yizhouwei** [comment]
@xuguangxin it seems that the problem has already solved.
I tested with .yv12 files and the program printed unsupportted fourcc.
although it still abortted in the end.

**Comment by xuguangxin** [comment]
seems this fixed
