### ISSUE TITLE
can't create a jpeg encoder

### ISSUE THREAD

**Issue by qianzhang5** [01org/libyami#442]
command>  "tests/yamiencode -i ~/Videos/out_1920x1080.yuv -W 1920 -H 1080  -s I420  -o  zzz.jpeg"
> libyami error 22304 (vaapiencoder_host.cpp, 42): Failed to create encoder for mimeType: 'image/jpeg'

The encoder registered list could be overwritten.
**added one line trace code into "common/factory.h"**
-   static bool register_(const KeyType& key)
-      {
- 	printf("TRACE--- registered %s %d \t %p\n", key.data(), (int)getCreators().size(), getCreators());
-         std::pair<iterator, bool> result =
-             getCreators().insert(std::make_pair(key, create<C>));
-         return result.second;
-      }

**with same test command, I ge**t

- TRACE--- registered video/avc 0 	 0x7f457e460940
- TRACE--- registered video/h264 1 	 0x7f457e460940
- TRACE--- registered video/h265 2 	 0x7f457e460940
- TRACE--- registered video/x-vnd.on2.vp8 3 	 0x7f457e460940
- TRACE--- registered image/jpeg 4 	 0x7f457e460940
- TRACE--- registered video/avc 0 	 0x7f457e460980  <--- static registered list (creators) is changed!
- TRACE--- registered video/h264 1 	 0x7f457e460980
- TRACE--- registered vpp/scaler 0 	 0x7f457e4609e0

>libyami error 22319 (vaapiencoder_host.cpp, 42): Failed to create encoder for mimeType: 'image/jpeg'
lt-yamiencode: encode.cpp:75: int main(int, char**): Assertion `encoder != __null' failed.

**Comment by uartie** [comment]
There are actually 3 different factories (encoder, decoder, and video postprocess factories)... this is why you see 3 different addresses for the getCreators() return address.

What configuration options did you use?  Did you specify '--enable-jpegenc' in your configure options.  JPEG encoding is disabled by default.

**Comment by uartie** [comment]
`./autogen.sh --help` or `./configure --help` will show you what is enabled/disabled by default.

**Comment by qianzhang5** [comment]
After enable jpeg encoder, I got error by "tests/yamiencode -i
~/Videos/out_1920x1080.yuv -W 1920 -H 1080 -s I420 -o zzz.jpg"

libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
libyami error 30513 (vaapiutils.h, 62): vaCreateConfig : the requested
VAEntryPoint is not supported
libyami error 30513 (vaapiencoder_base.cpp, 453): failed to create config
lt-yamiencode: encode.cpp:96: int main(int, char**): Assertion `status ==
ENCODE_SUCCESS' failed.

CPU:
processor : 2
vendor_id : GenuineIntel
cpu family : 6
model : 58
model name : Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

I guess the profile is not correct. what you a right way to test jpeg
encoder?

**Comment by uartie** [comment]
JPEG hardware encode is not supported on i5-3470

**Comment by lizhong1008** [comment]
"vainfo" can check HW and libva-intel-driver can support JPEG Enc or not.

**Comment by qianzhang5** [comment]
vainfo: VA-API version: 0.38 (libva 1.6.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Ivybridge Desktop - 1.6.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD

**Comment by lizhong1008** [comment]
"VAProfileJPEGBaseline : VAEntrypointVLD", only Jpeg decoder supported.

**Comment by qianzhang5** [comment]
There should be a "hardware capabilities" API.

**Comment by chivakker** [comment]
@qianzhang5 you can use from your application:


VAStatus vaQueryConfigProfiles (
    VADisplay dpy,
    VAProfile *profile_list,	/* out */
    int *num_profiles		/* out */
);

VAStatus vaQueryConfigEntrypoints (
    VADisplay dpy,
    VAProfile profile,
    VAEntrypoint *entrypoint_list,	/* out */
    int *num_entrypoints		/* out */
);

**Comment by qianzhang5** [comment]
I'm fine for me with this solution, but for a user to use YAMI framework It's better not touch the vaapi layer again. as it seems to me isolating vaapi to provide a simple video interface is one of YAMI's goal.

**Comment by chivakker** [comment]
Yes definitely and we will address this problem so that libyami can report both profiles and entrypoints as well.

**Comment by xuguangxin** [comment]
this line means "libyami error 30513 (vaapiutils.h, 62): vaCreateConfig : the requested
VAEntryPoint is not supported" hardware accelerator is not supported. Maybe we can make it more clearer.

Hi all:
It's very tedious to provide hardware caps enumeration api. It's normally hard to use. And user only care about they can/can't create decoder. not care about the detailed hardware cpas. We'd better not provide some function set which just a simple wrapper to vaapi(one to one map). We'd can provide functions in higher level. 
Do you think it's enough to vaQueryConfigEntrypoints in createVideoXXX and return NULL if the request profile is not supported?

**Comment by chivakker** [comment]
I think in reality what's not supported is the Profile in this case, so an error message more useful can read: Profile VAProfilexxxx is not supported on this hardware. If the Entrypoint is the one missing then error can read: Entrypoint XXX is not supported on this hardware.

I agree we don't need to expose a one to one function with vaapi, but definitely we need to inform user when such conditions happen, i.e. yami has to call the query and iterate on the results before returning the error.

**Comment by uartie** [comment]
Close this issue... the original problem has been addressed.

Please open a different issue to discuss the hw capabilities query support.
