### ISSUE TITLE
provide an error message when Profile or Entrypoint are not supported

### ISSUE THREAD

**Issue by chivakker** [01org/libyami#443]
libyami client should have a meaningful error message displayed when either the Profile or Entrypoint are not supported.  User should realize that the particular generation of hardware doesn't support a Profile or Entrypoint that is going to be used. .

**Comment by uartie** [comment]
In addition, perhaps `yamiinfo` should be capable of relaying this information, too?

**Comment by xuguangxin** [comment]
This need run time driver caps check
