### ISSUE TITLE
yami encoder will pading the width

### ISSUE THREAD

**Issue by mypopy** [01org/libyami#453]
this issue can be reproduce used the yamitranscode.

1. yamitranscode -i skyfall2-trailer.mp4 -o 1111x720.264, then used the mediainfo check 1111x720.264, you will get the width is 1112, not 1111.

**Comment by lizhong1008** [comment]
For H264, if input yuv format is YUV420 or YUV422, luma_width is twice of chroma_width. Thus means luma_width should be multiples of two.
