### ISSUE TITLE
B Frames cause error displaying order for h264 sequence

### ISSUE THREAD

**Issue by hcg2008** [01org/libyami#457]
how to adjust the output order?

**Comment by hcg2008** [comment]
Finded reason:

my sequence has 3 refs, changing the following function in vaapidecoder_h264.cpp

numRefLists = 3;

bool VaapiDecoderH264::fillRefPicList(VASliceParameterBufferH264 * sliceParam,
                                        const SliceHeaderPtr& sliceHdr)
{
    uint32_t i, numRefLists = 0;
    VaapiDecPicBufLayer::Ptr& DPBLayer = m_DPBManager->DPBLayer;

    sliceParam->num_ref_idx_l0_active_minus1 = 0;
    sliceParam->num_ref_idx_l1_active_minus1 = 0;

    if (H264_IS_B_SLICE(sliceHdr))
        **numRefLists = 2;**
    else if (H264_IS_I_SLICE(sliceHdr))
        numRefLists = 0;
    else
        numRefLists = 1;
    ....
    if (**numRefLists < 2**)
        return true;

    ....
    return true;
}

**Comment by xuguangxin** [comment]
Hi @hcg2008 
Could you attach your file here.We have test this for B frame. it's no problem. Maybe it's related to special stream. Your finding should not be a root cause. Because  numRefLists is reflist count. The max value is 2. One for forward reference list, one for backward. it never be 3.

**Comment by hcg2008** [comment]
sorry, like your comment, it wasn't the real reason by more testing.

The reason should be gpu overload: 
if you using args -c 5 & -r 5 to run grid decoding 1080p 264 sequence, you will find picture flipping like frame reversing.
My laptop CPU: I5-3317U 1.7G

After I added usleep() in grid.cpp, the display seem to be normal. 
The example's render didn't control the output frame rates.

void renderOutputs()
716     {
717         SharedPtr<VideoFrame> frame;
718         FpsCalc fps;
719         int width = m_width / m_col;
720         int height = m_height / m_row;
721         do {
742         ......
743             **usleep(20*1000);**
744 
745             fps.addFrame();
746         } while (1);
747 DONE:
748         printf("playback on display %d done\n", m_displayIdx);
749         fps.log();
750     }

**Comment by xuguangxin** [comment]
frame reversing? You mean gitter?
