### ISSUE TITLE
run2run is not bit match in h264 encoder

### ISSUE THREAD

**Issue by mypopy** [01org/libyami#459]
When setting ipperiod with 3 for 1920x1080 h.264 encoder, run2run  is not bit match in h264 encoder

root@tests# ./yamiencode -i ../../ffmpeg_yami_testcast/foo-200.yuv -W 1920 -H 1080 -N 100 -s NV12 -c AVC --ipperiod 3 -o test-3-1.h264
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
WARNING: Input ref list is Wrong !
encode done

root@tests# ./yamiencode -i ../../ffmpeg_yami_testcast/foo-200.yuv -W 1920 -H 1080 -N 100 -s NV12 -c AVC --ipperiod 3 -o test-3-2.h264
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
WARNING: Input ref list is Wrong !
encode done

root@media-Crown-Ridge:/home/media/Project/yami/libyami-master/tests# ls -al test-3*
-rw-r--r-- 1 root root **1240731** Mar 22 10:18 test-3-1.h264
-rw-r--r-- 1 root root **1240813** Mar 22 10:18 test-3-2.h264

test-3-1.h264 and test-3-2.h264 is not bit match in this case.

**Comment by xuguangxin** [comment]
gstreamer vaapi have this issue too.
Please report this to libva

> DISPLAY=:0 gst-launch-1.0 filesrc location=~/bits/320x240.264 ! h264parse ! vaapidecode ! vaapiencode_h264 ! filesink location=a.264
> DISPLAY=:0 gst-launch-1.0 filesrc location=~/bits/320x240.264 ! h264parse ! vaapidecode ! vaapiencode_h264 ! filesink location=b.264
> diff a.264 b.264
