### ISSUE TITLE
yamitranscode can't work when setting ipperiod more than 5

### ISSUE THREAD

**Issue by mypopy** [01org/libyami#461]
In master branch, yamitranscode can't work when setting ipperiod more than 5.

tests# ./yamitranscode -i ../../ffmpeg_yami_testcast/1920x1080.h264 -o 1920x1080.h264 -ipperiod 6
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
**libyami error 25834 (yamitranscode.cpp, 279): failed to get output frame**
6 frame decoded, fps = 176.47. fps after 5 frames = 1000.00.
transcode done

tests# ./yamitranscode -i ../../ffmpeg_yami_testcast/1920x1080.h264 -o 1920x1080.h264 -ipperiod 5
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
WARNING: Input ref list is Wrong !
3614 frame decoded, fps = 49.65. fps after 5 frames = 49.68.
transcode done

**Comment by xuguangxin** [comment]
hi @mypopy 
Do we still have this problem in apache?

**Comment by mypopydev** [comment]
Now its will block when ipperiod > 9 in our test env

**Comment by xuguangxin** [comment]
Hi Dongping:
Please help to fix this

**Comment by wudping** [comment]
ok.

**Comment by xuguangxin** [comment]
Hi @mypopy ,
this fixed by https://github.com/01org/libyami-utils/pull/11
