### ISSUE TITLE
Libyami encoder only support CQP/CBR ratecontrol method

### ISSUE THREAD

**Issue by mypopydev** [01org/libyami#470]
VAAPI can support CQP/CBR/VBR/VCM ratecontrol methood, but libyami just support  CQP/CBR ratecontrol method.

**Comment by xuguangxin** [comment]
Interface defined VBR and VCM. But the driver only support CQP and CBR mode.

**Comment by xuguangxin** [comment]
Hi @mypopydev 
Do you think it's ok to close this?

**Comment by mypopy** [comment]
You can closed it.

2016-07-06 11:57 GMT+08:00 Xu Guangxin notifications@github.com:

> Hi @mypopydev https://github.com/mypopydev
> Do you think it's ok to close this?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/01org/libyami/issues/470#issuecomment-230665455, or mute
> the thread
> https://github.com/notifications/unsubscribe/AA0HYTTLeE4w9jT6JRnIfCWoAq44xC9Xks5qSye1gaJpZM4IdqQ3
> .

## 

# 

Pixelworks
Room 301-303 No. 88,Lane 887 Zuchongzhi Road, Zhangjiang Hi-tech Park,
Shanghai 201203, China
Best Regards,
Jun zhao/赵军
+++++++++++++++++++++++++++++++++++++++

**Comment by xuguangxin** [comment]
ok,thanks
