### ISSUE TITLE
codec parser for mpeg2  unit test failed.

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#479]
all mpeg unit test failed as below

> [  FAILED  ] MPEG2ParserTest.ParseSlice (0 ms)
> [----------] 6 tests from MPEG2ParserTest (0 ms total)
> 
> [----------] 2 tests from VC1ParserTest
> [ RUN      ] VC1ParserTest.ParseSequenceHeader
> [       OK ] VC1ParserTest.ParseSequenceHeader (0 ms)
> [ RUN      ] VC1ParserTest.ParseFrameHeader
> [       OK ] VC1ParserTest.ParseFrameHeader (0 ms)
> [----------] 2 tests from VC1ParserTest (0 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 29 tests from 7 test cases ran. (660 ms total)
> [  PASSED  ] 23 tests.
> [  FAILED  ] 6 tests, listed below:
> [  FAILED  ] MPEG2ParserTest.ParseSequenceHeader
> [  FAILED  ] MPEG2ParserTest.ParseSequenceExtension
> [  FAILED  ] MPEG2ParserTest.ParseGOPHeader
> [  FAILED  ] MPEG2ParserTest.ParsePictureHeader
> [  FAILED  ] MPEG2ParserTest.ParsePictureCodingExtension
> [  FAILED  ] MPEG2ParserTest.ParseSlice

**Comment by chivakker** [comment]
I am checking this report
