### ISSUE TITLE
encoder unit test failed.

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#480]
all encoder unit test failed as below:

> [==========] Running 7 tests from 5 test cases.
> [----------] Global test environment set-up.
> [----------] 1 test from VaapiEncoderH264Test
> [ RUN      ] VaapiEncoderH264Test.Factory
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test fixture's constructor.
> [  FAILED  ] VaapiEncoderH264Test.Factory (0 ms)
> [----------] 1 test from VaapiEncoderH264Test (0 ms total)
> 
> [----------] 1 test from VaapiEncoderHEVCTest
> [ RUN      ] VaapiEncoderHEVCTest.Factory
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test fixture's constructor.
> [  FAILED  ] VaapiEncoderHEVCTest.Factory (0 ms)
> [----------] 1 test from VaapiEncoderHEVCTest (0 ms total)
> 
> [----------] 1 test from VaapiEncoderJpegTest
> [ RUN      ] VaapiEncoderJpegTest.Factory
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test fixture's constructor.
> [  FAILED  ] VaapiEncoderJpegTest.Factory (0 ms)
> [----------] 1 test from VaapiEncoderJpegTest (0 ms total)
> 
> [----------] 1 test from VaapiEncoderVP8Test
> [ RUN      ] VaapiEncoderVP8Test.Factory
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test fixture's constructor.
> [  FAILED  ] VaapiEncoderVP8Test.Factory (0 ms)
> [----------] 1 test from VaapiEncoderVP8Test (0 ms total)
> 
> [----------] 3 tests from VaapiEncoderJpegTest/SimpleDataTest
> [ RUN      ] VaapiEncoderJpegTest/SimpleDataTest.Encode/0
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test fixture's constructor.
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/0, where GetParam() = "NV12" (1 ms)
> [ RUN      ] VaapiEncoderJpegTest/SimpleDataTest.Encode/1
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test fixture's constructor.
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/1, where GetParam() = "I420" (0 ms)
> [ RUN      ] VaapiEncoderJpegTest/SimpleDataTest.Encode/2
> unknown file: Failure
> C++ exception with description "std::bad_alloc" thrown in the test fixture's constructor.
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/2, where GetParam() = "YUY2" (0 ms)
> [----------] 3 tests from VaapiEncoderJpegTest/SimpleDataTest (1 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 7 tests from 5 test cases ran. (1 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 7 tests, listed below:
> [  FAILED  ] VaapiEncoderH264Test.Factory
> [  FAILED  ] VaapiEncoderHEVCTest.Factory
> [  FAILED  ] VaapiEncoderJpegTest.Factory
> [  FAILED  ] VaapiEncoderVP8Test.Factory
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/0, where GetParam() = "NV12"
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/1, where GetParam() = "I420"
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/2, where GetParam() = "YUY2"
> 
>  7 FAILED TESTS

**Comment by uartie** [comment]
Which OS? Which version of gtest?  Can you attach your configure output?  All except the last 3 pass for me.  And the last three fail for different reason on my system than reported here.

**Comment by xuguangxin** [comment]
14.04.1-Ubuntu. gtest 1.7.0, wired thing is if i run unittest more times. I will see 3 items pass too.
But it's pass or failed is totally random.

> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/2, where GetParam() = "YUY2" (0 ms)
> [----------] 3 tests from VaapiEncoderJpegTest/SimpleDataTest (1 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 7 tests from 5 test cases ran. (1 ms total)
> [  PASSED  ] 4 tests.
> [  FAILED  ] 3 tests, listed below:
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/0, where GetParam() = "NV12"
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/1, where GetParam() = "I420"
> [  FAILED  ] VaapiEncoderJpegTest/SimpleDataTest.Encode/2, where GetParam() = "YUY2"

**Comment by uartie** [comment]
The last three will always fail on HW older than SKL.

**Comment by uartie** [comment]
If you declare the destructors as `virtual` for VaapiEncoderH264, VaapiEncoderHEVC, and VaapiEncoderVP8, does it fix the std::bad_alloc errors?

Does `gdb` tell you anything?

**Comment by chivakker** [comment]
I can confirm that on the current ToT the use cases failing for me are due to being run on old hardware. This is 100% reproducible and expected.

**Comment by uartie** [comment]
This is a case where we need a mechanism to skip tests (or expect failure) on hw that doesn't support it.

**Comment by xuguangxin** [comment]
yes. may need add some caps query api

**Comment by xuguangxin** [comment]
@uartie ：
Seems if i disable jpeg encoder unit test, it will be good. I guess this maybe a gtest issue.

My local gtest env is from Lizhong, I want build my own to reproduce this issue. But it can't find gtest-config. Do we need do some thing for gtest-config? If yes, maybe we need add something to readme.

> checking whether make supports nested variables... (cached) yes
> checking for 'gtest-config'... no
> configure: error: Unable to locate either a built or installed Google Test.
> The specific location '/home/thomas/projects/yami/googletest-release-1.7.0' was provided for a built or installed
> Google Test, but no 'gtest-config' script could be found at this location.

**Comment by uartie** [comment]
The `gtest-config` script is generated during `configure`.  How are you building gtest?  I use the `autotools` method.  I don't think the `cmake` method generates rules for `gtest-config`.

This is how I build gtest:

```
cd <path to gtest source>
autoreconf -v --install
./configure --disable-shared --enable-static
make
```

...then to build libyami with gtest:

```
cd <path to libyami source>
./autogen.sh --enable-gtest=<path to gtest source> <other config args>
```

**Comment by xuguangxin** [comment]
Great! it's fixed by your method. 
I did see this command in gtest's readme.
Is it ok if I add this to readme?

thanks

**Comment by uartie** [comment]
yes

**Comment by xuguangxin** [comment]
created as #490

**Comment by xuguangxin** [comment]
close this since it's a gtest configuration issue
