### ISSUE TITLE
Libyami build failed: only absolute run-paths are allowed

### ISSUE THREAD

**Issue by achrisan** [01org/libyami#481]
I am getting the following build with the latest libyami (apache branch).
libtool: link: only absolute run-paths are allowed
Makefile:557: recipe for target 'libyami.la' failed
make[2]: **\* [libyami.la] Error 1

I am building on a Haswell system which has the below libva and video driver version installed. I only tried to build libyami - ./autogen.sh --prefix=\$LIBYAMI_PREFIX , and LIBYAMI_PREFIX is set to the libyami directory, it ran without errors, but when I do a make, I see the above error.

Here are the system details
system: Ubuntu 15.10
gcc version : 5.2.1 20151010
VA-API version: 0.38 (libva 1.6.2.pre1)
Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 1.6.2.pre1 (1.6.1-82-g9ce333f)

**Comment by uartie** [comment]
Remove the `\` in `--prefix=\$LIBYAMI_PREFIX`

**Comment by uartie** [comment]
It should be `--prefix=$LIBYAMI_PREFIX`

**Comment by achrisan** [comment]
thanks, that worked. I t builds fine now.

**Comment by uartie** [comment]
Another solution is `--prefix=\${LIBYAMI_PREFIX}` or `--prefix=${LIBYAMI_PREFIX}`

**Comment by xuguangxin** [comment]
Hi achrisan:
you can't copy the command directly from `https://github.com/01org/libyami/wiki/Build#example-script-for-build-environments`, you need source it first.

here is my eaxmple

> $ source ../env.sh
> *======================current configuration=============================
> - VAAPI_PREFIX:               /myopt/yami/vaapi
> - LIBYAMI_PREFIX:             /myopt/yami/libyami
> - LD_LIBRARY_PATH:            /myopt/yami/vaapi/lib/:/myopt/yami/libyami/lib/:/myopt/yami/gst/lib:
> - PATH:                       /myopt/yami/vaapi/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/thomas/depot_tools
>   *=========================================================================
> - vaapi:      git clean -dxf && ./autogen.sh --prefix=$VAAPI_PREFIX && make -j8 && make install
> - ffmpeg:     ./configure --prefix=$VAAPI_PREFIX && make -j8 && make install
> - libyami:    git clean -dxf && ./autogen.sh --prefix=$LIBYAMI_PREFIX --enable-tests --enable-tests-gles && make -j8 && make install

then you can copy and paste it:

> $git clean -dxf && ./autogen.sh --prefix=$LIBYAMI_PREFIX --enable-tests --enable-tests-gles && make -j8 && make install
