### ISSUE TITLE
[Apache] h264 decoder DPB implement not follow the h264 spec

### ISSUE THREAD

**Issue by mypopydev** [01org/libyami#494]
Now h264 decoder DPB management is not follow the h264 spec, and always used 16 surfaces, it's not a good action in the low memory system.

**Comment by lizhong1008** [comment]
We already followed the h264 DPB management spec, else it can't be decoded. 
16 decoded surfaces are the max value as spec. Yeah, we will optimize it to reduce DPB surfaces as h264 level value.

**Comment by lizhong1008** [comment]
Hi Donging:
     Let's discuss how to do it before you start to do it. I can give you some guideline.

**Comment by wudping** [comment]
Thanks LiZhong, ok.

**Comment by xuguangxin** [comment]
fixed by https://github.com/01org/libyami/pull/519
