### ISSUE TITLE
yami-utils project did not treat warning as error

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#498]
If you add this line to a build file, It will report a warning not error.

```
uint64_t v;
printf("%d", v);
```

see https://github.com/01org/libyami-utils/pull/1#issuecomment-228230975 for details.

**Comment by chivakker** [comment]
Fixed here https://github.com/01org/libyami-utils/pull/4/

**Comment by xuguangxin** [comment]
thanks Daniel.
