### ISSUE TITLE
Does the vpp support i420 to nv12 or nv12 to i420

### ISSUE THREAD

**Issue by zackxue** [01org/libyami#503]
In the yamivpp, it seem support, but in the VaapiPostProcessScaler, it seems that do not support?

**Comment by xuguangxin** [comment]
Yes, you can try this yamivpp 320x240.i420 1920x1080.nv12.  VaapiPostProcessScaler will convert any format for you, if driver supported it.

**Comment by xuguangxin** [comment]
Hi @zackxue 
I will close this, if you still have issue please reopen it.
thanks
