### ISSUE TITLE
mpeg2 yami decode can't get format change event

### ISSUE THREAD

**Issue by mypopydev** [01org/libyami#505]
When call yami decoder API, we need to get the YAMI_FORMAT_CHANGE status after call decode( ) function, then we can used getFormatInfo( ) to get some format info, but now, mpeg2 decoder can't get this status, it's will break getFormatInfo() function in this case.

**Comment by xuguangxin** [comment]
Hi @chivakker 
Caller need format change to get format information, but seems mpeg did not return this.

**Comment by chivakker** [comment]
@mypopydev can you explain  how your call tree looks like?  How different is from this below?

start (configBuffer); //does it include stream information? like initial buffers?
decode(videoBuffer); //is this the first stream information buffer?

//after the first call to decode with stream information with the Sequence Header Information you expect a FORMAT_CHANGE
getFormatInfo();

**Comment by mypopydev** [comment]
Yes, @chivakker, in our case, we put the stream information in the statr(configBuffer), and when first call the decode() or some format change, I need the DECODE_FORMAT_CHANGE status, then use the getFormatInfo() to get some infos.

**Comment by xuguangxin** [comment]
Hi @mypopydev 
Did you send codec data to start()? If yes, we may not generate format change. You need getFormatInfo after you call start.

**Comment by mypopydev** [comment]
@xuguangxin in h264/HEVC decoder, even if we put the extradata(VideoConfigBuffer.data for SPS/PPS) in start(), we can get the DECODE_FORMAT_CHANGE after call decode().

BTW: I will try your suggestion.

**Comment by xuguangxin** [comment]
Hi @lizhong1008 
Coulc you confirm h264 thing?If yes, maybe we need change h264dec's behavior. We need return format change only when we detect real change in stream.

**Comment by chivakker** [comment]
For Mpeg2.  You can call start with a config buffer that has stream information, the assumption is that such buffer will contain at least one valid nal unit from the stream.  Typically that nal unit could contain the SequenceHeader or not, but keep in mind that you can only send SequenceHeader once before starting vaapi for the first time.  

Per your description above I am sending a pull ruquest that should fix your problem.

**Comment by chivakker** [comment]
@mypopydev can you give the referenced patch a try?

**Comment by mypopydev** [comment]
@chivakker I will try this patch quickly, tks, and pls refer to the code review comments.

**Comment by lizhong1008** [comment]
H264dec will decode codec data in start(), then it may return YAMI_DECODE_FORMAT_CHANGE. I think it's ok because it will only happen at the first time.

**Comment by xuguangxin** [comment]
Hi @lizhong1008 
Seems VaapiDecoderH264::start only  return YAMI_FAIL or YAMI_SUCCESS. Jun's question is why we generate format change in decode when format is not changed.

**Comment by lizhong1008** [comment]
@xuguangxin if has codec_data and not AVCC format, start() will call decodeAvcRecordData and decode() function. Please refer: https://github.com/01org/libyami/blob/apache/decoder/vaapidecoder_h264.cpp#L1138

**Comment by lizhong1008** [comment]
@xuguangxin , we check YAMI_DECODE_FORMAT_CHANGE in funcion ensureContext() at slice level decoding. That's why put the extradata(VideoConfigBuffer.data for SPS/PPS, but without slice_data), we will get YAMI_DECODE_FORMAT_CHANGE when decoding slice. It happens on the first decode() called.

**Comment by lizhong1008** [comment]
For H264 decoding, we can move ensureContext() to decodeSps().  Then start() can get YAMI_DECODE_FORMAT_CHANGE

**Comment by mypopydev** [comment]
@xuguangxin @lizhong1008  and all:

I hope I can give more clearer question about this issue.

1). When the caller get the YAMI_DECODE_FORMAT_CHANGE event?
2). When the caller can use getFormatInfo() to get the stream format information?

Currently, I suppose start() just return  YAMI_FAIL or YAMI_SUCCESS, and the first decode() return YAMI_DECODE_FORMAT_CHANGE, or when format is  changed in decoding. Is it right? If not, can we get a clear answer for upper 2 question ?

**Comment by xuguangxin** [comment]
Hi @mypopydev:
1. start will return YAMI_SUCCESS, YAMI_FAIL, or other fail return in future, like unsupported profile. 
2. decode will return format change when it detected format change.(we falsely report a format change at first frame, we can change it late)
3. User need check really change in getFormatInfo, Like some one may only care about video size change to larger.

Hi @all
Do you think this make sense?

**Comment by mypopydev** [comment]
@xuguangxin 
It's make sense for me.

**Comment by seanvk** [comment]
@xuguangxin Sounds good to me.
