### ISSUE TITLE
[Request] Performance tune consider for transcode/decode

### ISSUE THREAD

**Issue by mypopydev** [01org/libyami#509]
Some consider for yami performance tune
1. Now yamidecode output the RAW data is slowly. The link [Copying Accelerated Video Decode Frame Buffers](https://software.intel.com/en-us/articles/copying-accelerated-video-decode-frame-buffers) give a SSE4 optimization for this case.
2. I have a quick try to split the encoder encode() / getOutput()  function in 2 thread, get some data in our test bed.
- yamitranscode(without vpp) do transcode (h264 1080p -> h264 1080p), fps = 79.87.
- Split encoder encode() / getOutput() in 2 thread, the same video fps = 89 .

**Comment by xuguangxin** [comment]
Hi @mypopydev 
For item 1, maybe you can create a untiled surface and use vpp to copy  to it, it use gpu do memcpy, should faster than SSE4 version.
For item 2, is it related to encoder params? I checked this using default param before. It do not have visible improvement. I can double check this late.

**Comment by mypopydev** [comment]
@xuguangxin 
Is VPP copy  deterministic in OTC gfx driver?

**Comment by chivakker** [comment]
These requests apply for libyami-utils and not libyami.  

Also, both yamidecode and yamitranscode are reference applications for libyami Clients to create their own applications.  It is good that you have a 2 threaded application that produces more fps but it is not in the scope of yamitranscode.  

For yamidecode we could improve the memory copy but it is not the main interest for the utilities project.
