### ISSUE TITLE
YAMI_VPP_OCL_BLENDER blend.cl error

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#515]
every float in blend.cl must add “f”
 y_dst = 0.299f \* (float4) (rgba[0].x, rgba[1].x, rgba[2].x, rgba[3].x);
    y_dst = mad(0.587f, (float4) (rgba[0].y, rgba[1].y, rgba[2].y, rgba[3].y), y_dst);
    y_dst = mad(0.114f, (float4) (rgba[0].z, rgba[1].z, rgba[2].z, rgba[3].z), y_dst);
    y_dst *= (float4) (rgba[0].w, rgba[1].w, rgba[2].w, rgba[3].w);
    y1_dst.x = mad(1 - rgba[0].w, y1.x, y_dst.x);
    y1_dst.y = mad(1 - rgba[1].w, y1.y, y_dst.y);
    y2_dst.x = mad(1 - rgba[2].w, y2.x, y_dst.z);
    y2_dst.y = mad(1 - rgba[3].w, y2.y, y_dst.w);

```
uv_dst.x = rgba[0].w * (-0.14713f * rgba[0].x - 0.28886f * rgba[0].y + 0.43600f * rgba[0].z + 0.5f);
uv_dst.y = rgba[0].w * ( 0.61500f * rgba[0].x - 0.51499f * rgba[0].y - 0.10001f * rgba[0].z + 0.5f);
uv_dst.x = mad(1 - rgba[0].w, uv.x, uv_dst.x);
uv_dst.y = mad(1 - rgba[0].w, uv.y, uv_dst.y);
```

the example/blend.cpp  
draw half red line, the result is not half red line.

  bool drawSurfaceRGBA(SharedPtr<VideoFrame>& frame)
    {
        VASurfaceID surface = (VASurfaceID)frame->surface;
        VAImage image;

```
    VAStatus status = vaDeriveImage(m_vaDisplay,surface,&image);
    if (!checkVaapiStatus(status, "vaDeriveImage"))
        return false;
    assert(image.num_planes == 1);
    char* buf;
    status = vaMapBuffer(m_vaDisplay, image.buf, (void**)&buf);
    if (!checkVaapiStatus(status, "vaMapBuffer")) {
        vaDestroyImage(m_vaDisplay, image.image_id);
        return false;
    }

    uint8_t  r = rand() % 256;
    uint8_t  g = rand() % 256;
    uint8_t  b = rand() % 256;
    uint8_t  a = rand() % 256;

    uint32_t pixel = (r << 24) | (g << 16) | (b << 8) | a;
    char* ptr = buf + image.offsets[0];
    fprintf(stderr,"pix-wi%dxx%d\n",image.width,image.height);
    for (int i = 0; i < image.height; i++) {
        uint32_t* dest = (uint32_t*)(ptr + image.pitches[0] * i);
        for (int j = 0; j < image.width; j++) {
            *dest = pixel;
                            // here changed
            if (i == image.width/2 && j <image.height/2){
                *dest = 0xff0000ff;
              }
            dest++;
        }
    }
    checkVaapiStatus(vaUnmapBuffer(m_vaDisplay, image.buf), "vaUnmapBuffer");
    checkVaapiStatus(vaDestroyImage(m_vaDisplay, image.image_id), "vaDestroyImage");
    return true;
}
```

**Comment by xuguangxin** [comment]
Hi @dspmeng 
Please help to answer this question. thanks.

**Comment by dspmeng** [comment]
1. blend.cl
   I don't find issue on my Haswell with latest beignet. But it's good suggestion to add float suffix. I can submit a fix.
2. blend.cpp
   There are tow issues in your change:
   a) i and j are reversed
   b) you'd better modify two row of pixels, because the background image is NV12 (UV are shared)
                                   // here changed
           if (i == image.width/2 && j <image.height/2){               <---- try "if ((i == image.height/2 || i == image.height/2 - 1) && j <image.width/2){"
               *dest = 0xff0000ff;
             }

**Comment by dspmeng** [comment]
fix in #567

**Comment by xuguangxin** [comment]
Hi @waiter89
Please help to verify.

**Comment by ghost** [comment]
RC1 test OK.
