### ISSUE TITLE
yami h264 decode one stream with different resolution format

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#516]
please see the test.h264,the older version yami is ok to decode

**Comment by xuguangxin** [comment]
Hi @waiter89 
 I did not see the file. Could you put the video file to somewhere. So we can download it.

**Comment by waiter89** [comment]
[test.zip](https://github.com/01org/libyami/files/380665/test.zip)

**Comment by xuguangxin** [comment]
thanks @waiter89

**Comment by xuguangxin** [comment]
Hi  @waiter89 
this fixed by #526, Could you check it

**Comment by xuguangxin** [comment]
fixed by #516

**Comment by ghost** [comment]
RC1 test OK.
