### ISSUE TITLE
Need to clear the VideoDecoderDefs.h/VIDEO_BUFFER_FLAG flags

### ISSUE THREAD

**Issue by mypopydev** [01org/libyami#521]
I find a lot of  flags  in VideoDecoderDefs.h/VIDEO_BUFFER_FLAG don't used in the core lib, need to clear them if don't use.

BTW: Only HAS_VA_PROFILE/HAS_SURFACE_NUMBER use in Vp8/h264/h265 decoder.

**Comment by xuguangxin** [comment]
We can remove them, but it maybe need move to next quarter, since we are busy with other things.

**Comment by mypopydev** [comment]
I will submit a patch for this :)

**Comment by xuguangxin** [comment]
Great! thanks

**Comment by xuguangxin** [comment]
fixed by https://github.com/01org/libyami-utils/pull/14
