### ISSUE TITLE
We should have one single header file for user to include.

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#538]
Currently we have many header files for user, 

> VideoDecoderHost.h
> VideoEncoderHost.h
> VideoPostProcessHost.h
> VideoDecoderCapi.h
> ...

How about create a file named Libyami.h (or LibyamiC.h for C api) , user need only include this single header file, they do not need know include details in Libyami.h.
Gstreamer’s gst.h is good example:
https://github.com/GStreamer/gstreamer/blob/master/gst/gst.h

**Comment by xuguangxin** [comment]
fixed by https://github.com/01org/libyami/pull/552

**Comment by ghost** [comment]
RC1 test OK.
