### ISSUE TITLE
[H264][decoder]decode fail with sps->mui.max_dec_frame_buffering is 0 

### ISSUE THREAD

**Issue by popkartyeah** [01org/libyami#545]
when sps->mui.max_dec_frame_buffering value is 0 in some streams (such as extreme-plane-pred.h264 in ffmpeg), the yamidecode will break, follow is yamidecode run result:
libva info: VA-API version 0.39.2
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
libyami error 16541 (vaapidecsurfacepool.cpp, 51): allocate surface failed (352x288), size = 0
VppInputDecode config failed.
DecodeTest init failed.
I think there was something wrong in vaapidecoder_h264.cpp.

**Comment by xuguangxin** [comment]
This may related to https://github.com/01org/libyami/issues/494.
@lizhong1008 , please help to check it

**Comment by lizhong1008** [comment]
@popkartyeah solved by c3714fa8db5b4b13afc7b963a5c1a7e989556379, please help to verify it.

**Comment by popkartyeah** [comment]
@lizhong1008 yeah, I think it had be fixed.
