### ISSUE TITLE
libyami command for VP8/VP9 encode and decode

### ISSUE THREAD

**Issue by laxigithub** [01org/libyami#549]
Could you help with the command to use for VP8/VP9 encode and decode.

**Comment by chivakker** [comment]
On Wed, Aug 31, 2016 at 1:47 PM, Laxman notifications@github.com wrote:

> Could you help with the command to use for VP8/VP9 encode and decode.

You can use libyami-utils tests as examples on how to use libyami.
 libyami-utils has a set of tests (yamidecode, yamiencode, yamitranscode)
that will exercise the enc/dec depending on your h/w and configuration.
libva utils (vainfo) can help you understand what is supported by your
hardware.  If the Entrypoint or profile doesn't show up with vainfo, then
your h/w is not supporting it and it won't work even if you compile libyami
with that codec.

With that said, you can configure libyami with the following options
--enable-vp8dec --enable-vp8enc --enable-vp9dec ( vp9 encoder is not merged
yet)

libyami-utils help can guide you

yamidecode --help
yamiencode --help
yamitranscode --help

## 

Daniel.
