### ISSUE TITLE
yami h264 decode one stream with different resolution format

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#559]
const VideoFormatInfo\* getFormatInfo() return a wrong resolution when decoding a  h264 stream with different resolution.
![192 168 1 136_16-09-06-15_52_6](https://cloud.githubusercontent.com/assets/10821071/18266057/5a43e1d8-744b-11e6-8bda-e7e6c41babb9.jpg)

**Comment by xuguangxin** [comment]
is this fix you problem? https://github.com/01org/libyami/pull/544/files

**Comment by waiter89** [comment]
Thanks，It's ok now

**Comment by ghost** [comment]
RC1 test ok.
