### ISSUE TITLE
compile error,std::auto_ptr  -> std::shared_ptr  

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#561]
In file included from vaapiDecoderJPEG.cpp:22:0:
vaapiDecoderJPEG.h:53:10: error: ‘template<class> class std::auto_ptr’ is deprecated [-Werror=deprecated-declarations]
     std::auto_ptrVaapiDecoderJPEG::Impl m_impl;
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/c++/6/tr1/memory:39,
                 from ../interface/VideoCommonDefs.h:27,
                 from ../vaapi/vaapipicture.h:20,
                 from vaapidecpicture.h:19,
                 from vaapiDecoderJPEG.h:21,
                 from vaapiDecoderJPEG.cpp:22:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: **\* [Makefile:700：libyami_decoder_la-vaapiDecoderJPEG.lo] 错误 1

 std::auto_ptr  change to  std::shared_ptr   ???
it's ok to compile when std::auto_ptr  change to  std::shared_ptr

**Comment by uartie** [comment]
Yes, since GCC version 6 the deprecation is treated as an error.  We can use SharedPtr instead (defined in VideoCommonDefs.h).

**Comment by xuguangxin** [comment]
We shold not use auto_ptr, is not well designed, shared_ptr is better than auto_ptr....Wired, I missed this in code review.
