### ISSUE TITLE
TR1 vs C++11

### ISSUE THREAD

**Issue by uartie** [01org/libyami#571]
We need to isolate the usage of tr1 and C++11 in the entire project.  We need a common interface that can be used that transparently uses either C++11 or TR1 APIs depending on compilation mode (i.e. ANDRIOD vs. everything else).  Currently, this is partially done in [VideoCommonDefs.h](https://github.com/01org/libyami/blob/apache/interface/VideoCommonDefs.h) and [Functional.h](https://github.com/01org/libyami/blob/apache/common/Functional.h).  However, there  are still a lot of files that include tr1 headers instead of the aforementioned headers.

Also, the `#define Bind ...` definition conflicts with gtest's definition of Bind... so this will need resolved.  We should try to avoid the `#define`  pattern, too.

@scott-d-phillips suggested that we might put `std::tr1::bind`, etc.. into the `std` namespace, for example:

```
namespace std {
  using std::tr1::bind;
};
```

... then we  could use `std::bind`, etc. throughout the code.

**Comment by d-scott-phillips** [comment]
also consider changing `#ifdef ANDROID` to `#if __cplusplus > 199711L` in cases where the conditional is really about language version and not about the platform itself.

**Comment by uartie** [comment]
I've started work on this... please assign to me.

**Comment by chivakker** [comment]
@uartie your name is not on the list yet.

**Comment by xuguangxin** [comment]
Hi @uartie , 
I have add you to collaboration list https://github.com/01org/libyami/settings/collaboration. But final solution is add you to 01org/media team at https://github.com/orgs/01org/teams/01-org-media . I do not know who have this right. Maybe @sean can help you.

**Comment by uartie** [comment]
Hi @xuguangxin ,
The 01org/media team link does not work for me.  I talked to @seanvk today and he's looking into getting me added.  Thanks.
