### ISSUE TITLE
[yamitranscode] Fail to guess input width and height even we provide one

### ISSUE THREAD

**Issue by ghost** [01org/libyami#578]
$ yamitranscode -i 1080p_blue_sky.yuv -s I420 -W 1920 -H 1080 -c AVC --rcmode CQP -t 1 --priorityid 4 --intraperiod 10 -o 1080p_blue_sky.h264

It should be remove guess w/h when the cmd line specified the weight and height.

**Comment by lizhong1008** [comment]
Sent a pull request as https://github.com/lizhong1008/libyami-utils/commit/43a09803ae976e3d1815a4867fc37e5f0804dce3. @wang-fei ,please help to verify it. Thanks
