### ISSUE TITLE
vp9 encode fails with special 2K yuv input

### ISSUE THREAD

**Issue by chivakker** [01org/libyami#582]
$ yamiencode -i somefile_300frames.yuv -s I420 -W 2048 -H 858 -c VP9 --rcmode CQP -o ./samefile_300frames.yuv.vp9
[IMGUTILS @ 0x7ffd372c02e0] Picture size 0x0 is invalid
libva info: VA-API version 0.39.3
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami//vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
libyami error 14466 (vaapipicture.cpp, 61): vaEndPicture(): invalid parameter
libyami error 14466 (encode.cpp, 126): assert fails
yamiencode: encode.cpp:126: int main(int, char**): Assertion `0 && (status == YAMI_SUCCESS)' failed.
Aborted (core dumped)

**Comment by ghost** [comment]
@chivakker , I checked with the following resolution and it seems image width and height should be alignd with 8. 
2560x1440 (normal 2k resolution)  Pass
198x150 (w/h aligned with 2)         Fail
396x300 (w/h aligned with 4)         Fail
792x600 (w/h aligned with 8)         Pass

**Comment by lizhong1008** [comment]
I see the comment in  in libva (va_enc_vp9.h), "The source and recon surfaces allocated should be 64x64(SB) aligned". We need do Align64(width) and Align64(heigh) when we create these surfaces.

**Comment by xuguangxin** [comment]
If we do need alloc  64 aligned surface, we should pay attention to unused area in right and bottom. 
see https://cgit.freedesktop.org/vaapi/intel-driver/commit/?id=a478779c8c6b296c2069ab0fbc6f71c2e55c6a85 for detials

**Comment by chivakker** [comment]
I confirmed that aligning it to 8 will make the use cases pass although the border clean is adding a green line in right and bottom.   I need to figure out a way to just do this only when creating the surfaces but keeping the file size the same.

Aligning to 64 will make the borders bigger, I'd prefer to align to 8; objections?

**Comment by xuguangxin** [comment]
fixed by #601

**Comment by ghost** [comment]
1.0.0 RC2 test OK.
