### ISSUE TITLE
We did not support none zero start point of crop window in h264 and h265.

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#591]
We always set crop window x, y to 0, 0, since codec parser do not carry out the value.
See https://github.com/01org/libyami/blob/apache/decoder/vaapidecoder_h264.cpp#L1674
and https://github.com/01org/libyami/blob/apache/codecparsers/h264Parser.cpp#L481 for details.

This make us failed on some conformance test. We need fix this in codecc parser.
H265 have this problem too.

**Comment by xuguangxin** [comment]
@wudping , Since you are try to fix similar issue in h265, please help to fix this in h264 too.
thanks

**Comment by wudping** [comment]
okay, you are welcome @xuguangxin ;

**Comment by xuguangxin** [comment]
@wudping , any update on this?

**Comment by wudping** [comment]
I have checked the failed decoding clips with crop information, but that problem can not be solved by invoking setFormat(). It needs more time.

**Comment by wudping** [comment]
will be fixed by pull request [714](https://github.com/01org/libyami/pull/714).

**Comment by xuguangxin** [comment]
fixed by #714 and #703
