### ISSUE TITLE
add H264 SVC-T CBR mode support to libyami

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#594]
SVC temporary scalability (see https://en.wikipedia.org/wiki/Scalable_Video_Coding) is important to real-time communication or IP camera users, It adjust reference order to make sure you can get some decode able frame when reference frame dropped. Currently, yami have SVC-T CQP support, We'd better support CBR when libva driver is ready

**Comment by lizhong1008** [comment]
merged as 0a241d2307d554b704c0eb0158b446adc9a9a1e2

**Comment by ghost** [comment]
test OK:
libyami: 1.0.1 RC1 tag
libyami-utils: 1.0.1 RC1 tag
libva: 1.7.3.pre1
libva-intel-driver: 1.7.3.pre1
