### ISSUE TITLE
[HEVC][encode] lose frame when set '--ipperiod' as 2.

### ISSUE THREAD

**Issue by ghost** [01org/libyami#598]
$ yamiencode -W xxx -H xxx -c HEVC -i input.I420 -o out.h265 --qp xxx --ipperiod 2
$ yamidecode -i out.h265 -m 0 -f I420

Then the dumped out.h265.I420 file size is less than input.I420. For the correct result, the file size should be same.

**Comment by lizhong1008** [comment]
Yeah, we need flush the last B frames in cached buffer. Bob has fixed the same issue for h264, I will port it to hevc.

**Comment by xuguangxin** [comment]
@wang-fei & @lizhong1008 why this passed in last test

**Comment by ghost** [comment]
@xuguangxin , last test happened in ww32, and info:
Libva: 1517fd276e12cac14c018d5a30792177eb6c59de
intel_driver: 1cd67951974c944b060e2d5d88a76abb34c0c99b
libyami: 509d0cda8071073e302a11b9f17cdfbc71144721 (apache)
libyami-utils: 5c1a7e28cb62bc2e1d76d75d2f5cb94cb060292b (master)

So I think there should be some patch after 509d0c caused this issue.

**Comment by lizhong1008** [comment]
@wang-fei , it should not regression, you can double-check the ww32 result.

**Comment by xuguangxin** [comment]
@lizhong1008 , Do we really need fix it if it's not regression? Seems it will introduce many code

**Comment by lizhong1008** [comment]
@xuguangxin , yeah, we need fix it, but maybe not this quarter release.

**Comment by lizhong1008** [comment]
I have discussed with dongping how to fix it.  @wudping will fix it.

**Comment by ghost** [comment]
Bug still exist in 1.0.0 RC2 test.

**Comment by xuguangxin** [comment]
@wudping ,could you double check this with wangfei?
thanks

**Comment by wudping** [comment]
okay, you are welcome.

**Comment by ghost** [comment]
By using 'Video analyzer Tool', the encoded file show the correct frame number. So this should be the other issue in hevc decode. I will close this issue and create a hevc decode bug to track it.
