### ISSUE TITLE
h264 decoding crash again

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#599]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fa84db1f700 (LWP 17047)]
0x00007fa8893a137f in YamiMediaCodec::VaapiDecoderH264::DPB::init (this=this@entry=0x2e3d328, picture=..., prevPicture=..., slice=slice@entry=0x7fa8282875e0, 
    nalu=nalu@entry=0x7fa84db1e910, newStream=<optimized out>, contextChanged=false, maxDecFrameBuffering=5) at vaapidecoder_h264.cpp:1004
1004    vaapidecoder_h264.cpp: 没有那个文件或目录.
(gdb) bt
#0  0x00007fa8893a137f in YamiMediaCodec::VaapiDecoderH264::DPB::init (this=this@entry=0x2e3d328, picture=..., prevPicture=..., slice=slice@entry=0x7fa8282875e0,

```
nalu=nalu@entry=0x7fa84db1e910, newStream=<optimized out>, contextChanged=false, maxDecFrameBuffering=5) at vaapidecoder_h264.cpp:1004
```
#1  0x00007fa8893a28a1 in YamiMediaCodec::VaapiDecoderH264::decodeSlice (this=this@entry=0x2e3d1a0, nalu=nalu@entry=0x7fa84db1e910) at vaapidecoder_h264.cpp:1766
#2  0x00007fa8893a295b in YamiMediaCodec::VaapiDecoderH264::decodeNalu (this=this@entry=0x2e3d1a0, nalu=nalu@entry=0x7fa84db1e910) at vaapidecoder_h264.cpp:1790
#3  0x00007fa8893a2aa3 in YamiMediaCodec::VaapiDecoderH264::decode (this=0x2e3d1a0, buffer=<optimized out>) at vaapidecoder_h264.cpp:1842
#4  0x00007fa88936c0b6 in YamiEncoderInput::ConsumeVideo (this=0x2e3d0b0, Apbuf=<optimized out>, Alen=<optimized out>, Aflag=<optimized out>) at ../yamidecoder.cpp:137
#5  0x00007fa8898a08e8 in sw_inputer_consume (Ainputer=0x2e3d6e0, Apbuf=0x7fa8101d2910, Alen=19324, Aflag=0) at ../encoder.cpp:288
#6  0x00007fa890592f95 in sw_inputer_consume (Ainputer=0x2e3d6e0, Apbuf=0x7fa8101d2910, Alen=19324, Aflag=0) at ../shanwei_proc/shanwei_proc.c:448
#7  0x00007fa881a4f4ce in VideoEncoder::Draw (this=0x30e2310, Aspot=0x2e3d6e0, Abuf=0x7fa8101d2910, Alen=19324, Aflag=0) at VideoEncoder.cpp:66
#8  0x00007fa8819cb92a in MuxCamera::OnSpotVideo (this=0x30e2070, Acam=0x2d64a60, Avframe=0x7fa81015b060) at BizNode.cpp:772
#9  0x00007fa8819ce523 in MuxVideoConsumer::Receive (this=0x30e1ea0, Asrc=0x2d64a60, Adat=0x7fa81015b060) at BizNode.h:574
#10 0x00007fa88197720e in Spreader::Deliver (this=0x2bedcc0, Aindex=2) at Spreader.cpp:101
#11 0x00007fa881979759 in Deliverer::operator() (this=0x2e0a480, Aarg=0x2e0a890) at Spreader.cpp:491
#12 0x00007fa88197c1e0 in GrThread::GrThread<Deliverer>(Deliverer&, void_, void_, bool)::A::Run() () at ../sharedinc/grthread.hpp:440
#13 0x00007fa88197c207 in GrThread::GrThread<Deliverer>(Deliverer&, void_, void_, bool)::A::proc(void*) () at ../sharedinc/grthread.hpp:444
#14 0x00007fa899b4e0a4 in start_thread () from /lib64/libpthread.so.0
#15 0x00007fa898fe9cbd in clone () from /lib64/libc.so.6

(gdb) p sps
$1 = {
  <std::tr1::__shared_ptr<YamiParser::H264::SPS, (__gnu_cxx::_Lock_policy)2>> = {
    _M_ptr = 0x7fa828efe030, 
    _M_refcount = {
      _M_pi = 0x7fa828bdd030
    }
  }, <No data fields>}
(gdb) p picture
$2 = (const YamiMediaCodec::VaapiDecoderH264::DPB::PicturePtr &) @0x2e3d300: {
  <std::tr1::__shared_ptr<YamiMediaCodec::VaapiDecPictureH264, (__gnu_cxx::_Lock_policy)2>> = {
    _M_ptr = 0x7fa828476b30, 
    _M_refcount = {
      _M_pi = 0x7fa8287f9290
    }
  }, <No data fields>}
(gdb) p m_prevPicture
$3 = {
  <std::tr1::__shared_ptr<YamiMediaCodec::VaapiDecPictureH264, (__gnu_cxx::_Lock_policy)2>> = {
    _M_ptr = 0x0, 
    _M_refcount = {
      _M_pi = 0x0
    }
  }, <No data fields>}

**Comment by xuguangxin** [comment]
Hi @waiter89 
could you dump the file for us, so we can add this to our daily regression, make it never failed again

**Comment by xuguangxin** [comment]
Hi @waiter89 
Also we will add more error bit test in Q4, so could you provide some error bitstream for us?
thanks

**Comment by xuguangxin** [comment]
Hi @waiter89 
any update on this?

**Comment by xuguangxin** [comment]
Hi @waiter89 
I will close this temporaryly, please reopen it if you dumped the clip for this.thanks
