### ISSUE TITLE
[HEVC][decode] lose frame when set encode file option '--ipperiod 2'.

### ISSUE THREAD

**Issue by ghost** [01org/libyami#606]
$ yamiencode -W xxx -H xxx -c HEVC -i input.I420 -o out.h265 --qp xxx --ipperiod 2
$ yamidecode -i out.h265 -m 0 -f I420

Then the dumped out.h265.I420 file size is less than input.I420. For the correct result, the file size should be same.

**Comment by xuguangxin** [comment]
this fixed by #622

**Comment by ghost** [comment]
test OK:
libyami: 1.0.1 RC1 tag
libyami-utils: 1.0.1 RC1 tag
libva: 1.7.3.pre1
libva-intel-driver: 1.7.3.pre1
