### ISSUE TITLE
There are mosaic frames from about 1000 frames in following video

### ISSUE THREAD

**Issue by LindaYu17** [01org/libyami#607]
http://vodcdn.video.taobao.com/oss/ali-video/3536edc0480d4eacb2a3718a452702ce/1453047226/video.mp4

**Comment by LindaYu17** [comment]
this is the cut off .h264 with only one mosaic frames(from 1000 to 1045 frames from orignal video.mp4). Since github does not accept .h264 file, I zip it. please unzip to get original one.
[final.zip](https://github.com/01org/libyami/files/502036/final.zip)

**Comment by xuguangxin** [comment]
fixed by #608
