### ISSUE TITLE
decode h264 Segmentation fault.

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#613]
(gdb) bt
#0  __atomic_add_dispatch (__val=1, __mem=0x12d) at /usr/include/c++/4.8/ext/atomicity.h:96
#1  _M_add_ref_copy (this=0x125) at /usr/include/c++/4.8/tr1/shared_ptr.h:128
#2  __shared_count (__r=..., this=0x34d53d8) at /usr/include/c++/4.8/tr1/shared_ptr.h:348
#3  __shared_ptr (this=0x34d53d0) at /usr/include/c++/4.8/tr1/shared_ptr.h:541
#4  shared_ptr (this=0x34d53d0) at /usr/include/c++/4.8/tr1/shared_ptr.h:985
#5  _Constructstd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264, std::tr1::shared_ptrYamiMediaCodec::VaapiDecPictureH264 > (__value=..., __p=0x34d53d0)

```
at /usr/include/c++/4.8/bits/stl_construct.h:83
```
#6  __uninit_copystd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264_, std::tr1::shared_ptrYamiMediaCodec::VaapiDecPictureH264_> (__result=0x34d53c0,

```
__last=0x7fff48010ca0, __first=0x7fff48010b20) at /usr/include/c++/4.8/bits/stl_uninitialized.h:75
```
#7  uninitialized_copystd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264_, std::tr1::shared_ptrYamiMediaCodec::VaapiDecPictureH264_> (__result=0x34d53c0,

```
__last=0x7fff48010ca0, __first=0x7fff48010b10) at /usr/include/c++/4.8/bits/stl_uninitialized.h:117
```
#8  __uninitialized_copy_astd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264_, std::tr1::shared_ptrYamiMediaCodec::VaapiDecPictureH264_, std::tr1::shared_ptrYamiMediaCodec::VaapiDecPictureH264 > (__result=0x34d53c0, __last=0x7fff48010ca0, __first=0x7fff48010b10) at /usr/include/c++/4.8/bits/stl_uninitialized.h:258
#9  __uninitialized_move_if_noexcept_astd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264_, std::tr1::shared_ptrYamiMediaCodec::VaapiDecPictureH264_, std::allocatorstd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264 > > (__alloc=..., __result=0x34d53c0, __last=0x7fff48010ca0, __first=0x7fff48010b10)

```
at /usr/include/c++/4.8/bits/stl_uninitialized.h:281
```
#10 std::vectorstd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264, std::allocatorstd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264 > >::_M_insert_aux

```
(this=0x13fa7e0, __position=..., __x=...) at /usr/include/c++/4.8/bits/vector.tcc:362
```
#11 0x00007fffe2ae7771 in std::vectorstd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264, std::allocatorstd::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264 > >::insert (this=this@entry=0x13fa7e0, __position=..., __x=...) at /usr/include/c++/4.8/bits/vector.tcc:127
#12 0x00007fffe2ae17b2 in YamiMediaCodec::VaapiDecoderH264::DPB::modifyReferenceList (this=this@entry=0x13fa7e0, picture=..., slice=slice@entry=0x3512230,

```
refList=..., refIdx=refIdx@entry=0 '\000') at vaapidecoder_h264.cpp:660
```
#13 0x00007fffe2ae450c in YamiMediaCodec::VaapiDecoderH264::DPB::initReference (this=this@entry=0x13fa7e0, picture=..., slice=slice@entry=0x3512230)

```
at vaapidecoder_h264.cpp:588
```
#14 0x00007fffe2ae4960 in YamiMediaCodec::VaapiDecoderH264::decodeSlice (this=this@entry=0x13fa650, nalu=nalu@entry=0x7fff4effc910) at vaapidecoder_h264.cpp:1776
#15 0x00007fffe2ae4b4b in YamiMediaCodec::VaapiDecoderH264::decodeNalu (this=this@entry=0x13fa650, nalu=nalu@entry=0x7fff4effc910) at vaapidecoder_h264.cpp:1790
#16 0x00007fffe2ae4c93 in YamiMediaCodec::VaapiDecoderH264::decode (this=0x13fa650, buffer=<optimized out>) at vaapidecoder_h264.cpp:1842
#17 0x00007fffe2aad045 in YamiEncoderInput::ConsumeVideo (this=0x13fa560, Apbuf=<optimized out>, Alen=<optimized out>, Aflag=<optimized out>) at ../yamidecoder.cpp:132
#18 0x00007fffe2fe69b8 in sw_inputer_consume (Ainputer=0x13fab90, Apbuf=0x7fff787e4380, Alen=23844, Aflag=0) at ../encoder.cpp:288

**Comment by xuguangxin** [comment]
could you provide the bitstream to us. It's hard to debug without it.

**Comment by xuguangxin** [comment]
Hi @waiter89 
Is it ok to add some dump function before you sent to yami. We can catch and replay the error bitstream. It will help us debug the code. It is hard to debug the issue if we only have stack.

**Comment by xuguangxin** [comment]
Hi @waiter89 
Any update on this?

**Comment by xuguangxin** [comment]
Hi @waiter89 
I will close this temporaryly, please reopen it if you dumped the clip for this.thanks
