### ISSUE TITLE
Decode vp8 stream from libvpx results in video with macroblocks

### ISSUE THREAD

**Issue by taste1981** [01org/libyami#620]
the vp8 decoder, when decoding attached vp8 stream(unzip to output.ivf), will show many macroblocks and unexpected color blocks. This does not happen if we decode using libvpx.

[output.zip](https://github.com/01org/libyami/files/532372/output.zip)

**Comment by xuguangxin** [comment]
Seems it's a vp8 conformance issue after 169 frames

**Comment by chivakker** [comment]
I'll take a look and report back.  I have to confirm a fix is in place.

**Comment by ghost** [comment]
I try to use "yamidecode -i output.ivf -f I420 -m 0" to dump yuv file, but it returns an error. @xuguangxin @chivakker How can I verify this issue ?

root@yami-kbl:~# yamidecode -i output.ivf -f I420 -m 0
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami//vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
fail to read frame data, quit
got fatal error -1021
VppInputDecode config failed.
DecodeTest init failed.
root@yami-kbl:~#

Env:
libyami: 1.0.1 RC1 tag
libyami-utils: 1.0.1 RC1 tag
libva: 1.7.3.pre1
libva-intel-driver: 1.7.3.pre1

**Comment by xuguangxin** [comment]
Hi Fei:
The file dumped by @taste1981 have some issue.I fixed it, and i can mail to you. Please add this file to regression test set.
thanks

**Comment by ghost** [comment]
test OK:
libyami: 1.0.1 RC1 tag
libyami-utils: 1.0.1 RC1 tag
libva: 1.7.3.pre1
libva-intel-driver: 1.7.3.pre1
