### ISSUE TITLE
WebRTC: Encoded vp8 stream contains yellow color blocks and video quality not good

### ISSUE THREAD

**Issue by taste1981** [01org/libyami#633]
transcoding the vp8 stream I shared for issue #620  to 1080p-vp8-4Mbps@30fps, we get output vp8 stream with many yellow color blocks on the video, and video quality is not very good.

**Comment by taste1981** [comment]
driver 1.7.0 and 1.7.2 are checked. CBR mode is used for encoding.

**Comment by xuguangxin** [comment]
This is driver's issue, Haihao will working on this

**Comment by xuguangxin** [comment]
this is a driver's issue, lable it as won't fix

**Comment by xuguangxin** [comment]
close this since it's a driver's issue
