### ISSUE TITLE
Remove extra VPP in  V4l2Decode

### ISSUE THREAD

**Issue by halleyzhao** [01org/libyami#640]
libyami alloc video surface by itself.
in order to support buffer assigned from client, v4l2decode introduce extra video-post-processing to copy/convert yami video frame to client buffer.
this extra vpp process introduce additional GPU load, memory consumption, extra power consumption as well.

we'd remove this vpp process, to let yami core accept extra buffer.

**Comment by seanvk** [comment]
I have no objections.  I believe we added it in the first place as a part of Android and then to Wayland.  This was a part of the dealing with display and color format conversion.  I agree we should not presume that.

@xuguangxin, any concern?

**Comment by xuguangxin** [comment]
Hi @seanvk:
My big concern is schedule. We need change many things to make it work:
1. We need to adjust core library. To return format change before we actually allocate the decoder surface. This gives v4l2/omx a chance to ask surfaces from display
2. We need to adjust v4l2decoder, it needs pause decoder task before upper layer allocates surface from display and send to him.
3. We need to consider seek things. How to handle decoded surface on screen if we seek the video.
4. It may need 2-man month for this. Work on android then port to v4l2 will not meet Halley’s schedule.

Other thing I should mention is,  Halley does not expect us provide wayland solution, wayland have been wrapped to yalloc. They prefer us provide yalloc solution or dmb buf solution (Linda will do some wrapper on top of this)

**Comment by seanvk** [comment]
Yes, I understand.  But we've not received a clear description yet.  Is this for:  Android or YunOS?  Does this support require integration of Yalloc support?  We don't support (a) Android and we cannot support (b) Yalloc unless it is open source.

Also we need to consider the impact to other customer use cases with V4L2.  So in your list @xuguangxin  I agree with exception of that we don't support Android.  It is not POR.  So this work would have to be entirely open source and upstream focused.  No closed source Yalloc and no Android.

Thanks,

Sean

**Comment by xuguangxin** [comment]
Hi @halleyzhao 
Could you give more detail to sean?
thanks

**Comment by xuguangxin** [comment]
this is done by https://github.com/01org/libyami/commit/e46f03b63e5850016391845e5a14fb9f2f2b8aea
and https://github.com/01org/libyami-utils/commit/0cc8440778b92e3b5c20cb6a1008f9f978ff47cd
