### ISSUE TITLE
add libyami to debian package system

### ISSUE THREAD

**Issue by YuJiankang** [01org/libyami#642]
Xu, Guangxin added a comment - 17/Oct/16 8:05 AM
contacted debian media team, get replay here http://lists.alioth.debian.org/pipermail/pkg-multimedia-maintainers/2016-August/053665.html
will prepare debian package and scan for package error first.
I have build the debian package, scan for error and sent request to libva debian maintiainer. Hope he can help us add this package to debian

**Comment by seanvk** [comment]
Are we good?  Did we get into Debian now?  Can you share a link?

Sean

**Comment by xuguangxin** [comment]
Close this since it's in planning.
