### ISSUE TITLE
add libyami to yocto package system

### ISSUE THREAD

**Issue by YuJiankang** [01org/libyami#643]

**Comment by seanvk** [comment]
What is the status?

**Comment by wudping** [comment]
Hi @seanvk ,
Yocto build, build script is ready. However, 1.0.0 need some patches, we have upstream those patches for 1.0.1. We will send to yocto team after 1.0.1 released. (Due day WW47.5)

**Comment by xuguangxin** [comment]
Hi @seanvk ,
Dongping have built and done simple test on yocto. 

Hi @wudping , 
could attach current build script here. It’s good if we can get some suggestion from Sean.

**Comment by wudping** [comment]
Hi @seanvk , the following is part of libyami .bb file, our development is merely completed now, we will release it in version 1.0.1:

SUMMARY = "Yami is media infrastructure base on libva"
DESCRIPTION = "Yami is core building block for media solution; \
with efficient/simple APIs, without external dependency. It parses \
video stream and decodes/encodes them leverage hardware acceleration. \
It targets two type of usage: \
    Hardware accelerated codec is the only gap. \
    Usage is simple enough to be interested in codec only. \
Yami servers as develop kit for VAAPI, it has rich tests/examples to \
demonstrate/verify vaapi features. The tests can run without Window \
system (X11/Wayland etc), also supports advanced feature like texture \
video (dma_buf etc)."

HOMEPAGE = "https://github.com/01org/libyami"
BUGTRACKER = "https://github.com/01org/libyami/issues/new"

LICENSE = "Apache V2"
SRC_URI = "https://github.com/01org/libyami/archive/${BPN}-${PV}.tar.gz \
           file://0891-makefile-add-top_srcdir-into-cppflags.patch \
          "

LIC_FILES_CHKSUM = "file://COPYING.LIB;md5=3b83ef96387f14655fc854ddc3c6bd57"

SRC_URI[md5sum] = "068b89ca6331044a95a082cdfa38ffd7"
SRC_URI[sha256sum] = "ef83e0d279b387e8475cdd5898a9a00132fabaadd4a5b6224f707a31cd159af5"

S = "${WORKDIR}/libyami-libyami-${PV}"

PACKAGECONFIG ??= "${@bb.utils.contains("DISTRO_FEATURES", "x11", "x11", "", d)}"
PACKAGECONFIG[x11] = "--enable-x11,--disable-x11,virtual/libx11 libxrandr libxrender"

DEPENDS = "libva"
inherit autotools pkgconfig

#EXTRA_OECONF = " --disable-md5"

FILES_${PN} += "${libdir}/_.so"
FILES_${PN}-dev += "${libdir}/_.la"
FILES_${PN}-dbg += "${libdir}/.debug"

**Comment by xuguangxin** [comment]
Close this since it's in planning.
