### ISSUE TITLE
[HEVC][Encode] 4K resolution segment fault when set '--ipperiod 2'.

### ISSUE THREAD

**Issue by ghost** [01org/libyami#646]
4K resolution segment fault, other options for 4K and other resolutions looks good.

root@yami-kbl:~/media_libyami/encode_hevc# yamiencode -W 3840 -H 2160 -i /media/encoderbitstreams/4K_2013_3840_2160_300frames.yuv -o 4K_2013_3840_2160_300frames.yuv.enc.h265 --ipperiod 2
[IMGUTILS @ 0x7ffef79169b0] Picture size 0x0 is invalid
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami//vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
Segmentation fault (core dumped)

test env:
libyami: 1.0.1 RC1 tag
libyami-utils: 1.0.1 RC1 tag
libva: 1.7.3.pre1
libva-intel-driver: 1.7.3.pre1

**Comment by xuguangxin** [comment]
this may realted to avformat, could you disable avformat and try again?

**Comment by xuguangxin** [comment]
> [IMGUTILS @ 0x7ffef79169b0] Picture size 0x0 is invalid

**Comment by ghost** [comment]
@xuguangxin , after disable avforamt, "[IMGUTILS @ 0x7ffef79169b0] Picture size 0x0 is invalid" is gone. But segment fault still exist.

**Comment by xuguangxin** [comment]
@lizhong1008 , Do you have time to look at this?

**Comment by lizhong1008** [comment]
I checked it, no segment fault found. @wang-fei what's your configure option? Maybe you can reset your environment and try it again.

**Comment by ghost** [comment]
@lizhong1008 , It seem this issue is not always happen. I check it with dongping's env and add '--qp 10' seems more easy to see segment fault.

**Comment by lizhong1008** [comment]
@wang-fei  Still can not reproduce it. here is my configuration: ./autogen --prefix=/opt/yami/yami --enable-tests --enable-h265dec --enable-h265enc

**Comment by xuguangxin** [comment]
@wang-fei , any update on this?

**Comment by ghost** [comment]
I tried '--ipperiod 0' also get segment(not always), and here is some gdb info:
(gdb) set args -W 3840 -H 2160 -i /media/encoderbitstreams/4K_2013_3840_2160_300frames.yuv -o ./4K_2013_3840_2160_300frames.yuv_10_0.enc.h265 --qp 10 --ipperiod 0
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
The program being debugged has been started already.
Starting program: /opt/yami/libyami/bin/yamiencode -W 3840 -H 2160 -i /media/encoderbitstreams/4K_2013_3840_2160_300frames.yuv -o ./4K_2013_3840_2160_300frames.yuv_10_0.enc.h265 --qp 10 --ipperiod 0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main (argc=13, argv=0x7fffffffe238) at encode.cpp:38
(gdb) c
Continuing.
[0;39m[IMGUTILS @ 0x7fffffffdce0] [0m[1;31mPicture size 0x0 is invalid
[0mlibva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami//vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0

Program received signal SIGSEGV, Segmentation fault.
YamiMediaCodec::VaapiCodedBuffer::size (this=0x1b76f40) at vaapicodedbuffer.cpp:50
(gdb) bt
#0  YamiMediaCodec::VaapiCodedBuffer::size (this=0x1b76f40) at vaapicodedbuffer.cpp:50
#1  0x00007ffff7b7aad8 in YamiMediaCodec::VaapiEncPicture::getOutput (this=0x1b76cd0, outBuffer=0x7fffffffddc0) at vaapiencpicture.cpp:81
#2  0x00007ffff7b9b389 in std::tr1::function<YamiStatus ()>::operator()() const (this=<optimized out>) at /usr/include/c++/5/tr1/functional:2146
#3  YamiMediaCodec::VaapiEncPictureHEVC::getOutput(VideoEncOutputBuffer*, std::vector<std::tr1::function<YamiStatus ()>, std::allocator<std::tr1::function<YamiStatus ()> > >&) (functions=std::vector of len
gth 2, capacity 2 = {...}, outBuffer=0x7fffffffddc0, this=<optimized out>) at vaapiencoder_hevc.cpp:830
#4  YamiMediaCodec::VaapiEncPictureHEVC::getOutput (this=<optimized out>, outBuffer=0x7fffffffdf10) at vaapiencoder_hevc.cpp:796
#5  0x00007ffff7b7cdff in YamiMediaCodec::VaapiEncoderBase::getOutput (this=0x1b40b60, outBuffer=0x7fffffffdf10, withWait=<optimized out>) at vaapiencoder_base.cpp:574
#6  0x000000000045c428 in main (argc=<optimized out>, argv=<optimized out>) at encode.cpp:146
(gdb)

**Comment by ghost** [comment]
I will try to use 'valgrind' to get more information in Q4 release test.

**Comment by ghost** [comment]
Didn't meet this issue in 1.1.0 RC1 test. close it.
