### ISSUE TITLE
[Encode][AVC] 1080P encode block when set --qp as 4.

### ISSUE THREAD

**Issue by ghost** [01org/libyami#657]
1. setps
root@yami-skl:~/media_libyami/encode_h264# yamiencode -c AVC -s I420 -W 1920 -H 1080 --rcmode CQP -i /media/encoderbitstreams/1080p_blue_sky.yuv -o ./1080p_blue_sky_ip_gop30_fps30_qp4_lf10.h264 --qp 4 --ipperiod 1 --intraperiod 30
[IMGUTILS @ 0x7ffe5d4148d0] Picture size 0x0 is invalid
libva info: VA-API version 0.39.3
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/yami//vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0

This happens only under 1080P solution and qp as 4.

2.test env;
libva: 1.7.3.pre1
intel-driver: 1.7.3.pre1
libyami: ea3bc346870f912c81ab5842ecfd7e4a1a267827
libyami-utils: 3c6bbb5a04602b866528d1ba7987583dda16fe8b

**Comment by xuguangxin** [comment]
Hi @lizhong1008 
Do you have time to look at it ?

**Comment by lizhong1008** [comment]
@xuguangxin Yeah, I will check it. @wang-fei what does the "block" mean? Infinite loop for CPU or GPU ?

**Comment by ghost** [comment]
@lizhong1008, not infinite loop, just keep staying at 'libva info: va_openDriver() returns 0'. Need press ctrl+c to finish cmd.

**Comment by xuguangxin** [comment]
qp = 0 do not have this problem?

**Comment by ghost** [comment]
@xuguangxin qp=0 also has this issue.

**Comment by wudping** [comment]
hi @wang-fei , @xuguangxin ,
I have pushed a patch to fix this issue:
https://github.com/01org/libyami-utils/pull/72
please help to review and verify

Thanks

**Comment by xuguangxin** [comment]
fixed by https://github.com/01org/libyami-utils/pull/72

**Comment by feiwan1** [comment]
Verified OK in libyami 1.2.0 RC1 test with libva/intel-vaapi-driver 1.8.0 pre3.

**Comment by xuguangxin** [comment]
close this since it fixed
