### ISSUE TITLE
[H264][Encode][Vdenc] Encoder will trap to infinite loop when we set some parameter to it

### ISSUE THREAD

**Issue by ghost** [01org/libyami#675]
1. Fail case:
yamitranscode -i /media/encoderbitstreams/stockholm_1280x720_604.yuv -s I420 -W 1280 -H 720 -b 15000 -c AVC --rcmode CBR --ipperiod 1 --lowpower -f 3000 -o ./stockholm_1280x720_604.yuv_15000_1.h264
yamitranscode -i /media/encoderbitstreams/stockholm_1280x720_604.yuv -s I420 -W 1280 -H 720 -b 20000 -c AVC --rcmode CBR --ipperiod 1 --lowpower -f 3000 -o ./stockholm_1280x720_604.yuv_20000_1.h264
yamitranscode -i /media/encoderbitstreams/stockholm_1280x720_604.yuv -s I420 -W 1280 -H 720 -b 30000 -c AVC --rcmode CBR --ipperiod 1 --lowpower -f 3000 -o ./stockholm_1280x720_604.yuv_30000_1.h264
yamitranscode -i /media/encoderbitstreams/CITY_704x576_30_orig_01.yuv -s I420 -W 704 -H 576 -b 10000 -c AVC --rcmode CBR --ipperiod 1 --lowpower -f 3000 -o ./CITY_704x576_30_orig_01.yuv_10000_1.h264
yamitranscode -i /media/encoderbitstreams/CITY_704x576_30_orig_01.yuv -s I420 -W 704 -H 576 -b 16000 -c AVC --rcmode CBR --ipperiod 1 --lowpower -f 3000 -o ./CITY_704x576_30_orig_01.yuv_16000_1.h264
yamitranscode -i /media/encoderbitstreams/CITY_704x576_30_orig_01.yuv -s I420 -W 704 -H 576 -b 25000 -c AVC --rcmode CBR --ipperiod 1 --lowpower -f 3000 -o ./CITY_704x576_30_orig_01.yuv_25000_1.h264

Note: Use '-f 3000' is just a workaround for a bug from libva, actually it will be deal as '-f 30' inside libva.

2. Test env;
libva: 1.7.3.pre1
intel-driver: 1.7.3.pre1
libyami: 2ff190f56644b64d62e323ab92399296a50b045a
libyami-utils: 70461e9a5f2d4385cf24cf0352f2f3f0ed442946

3. Gdb info:
(gdb) bt
#0  VppOutputEncode::output (this=0x1b66340, frame=...) at vppoutputencode.cpp:194
#1  0x0000000000463ff9 in TranscodeTest::run (this=this@entry=0x7fffffffdfa0) at yamitranscode.cpp:387
#2  0x000000000045d223 in main (argc=22, argv=0x7fffffffe1b8) at yamitranscode.cpp:427
(gdb) p status
$7 = YAMI_ENCODE_BUFFER_TOO_SMALL
(gdb)

**Comment by xuguangxin** [comment]
fixed by #69

**Comment by ghost** [comment]
verified OK:
libva: 1.7.3.pre1
intel-driver: 1.7.3.pre1
libyami: 2ff190f
libyami-utils: f051729d0f457f9227d20afcb3c64c2347cd0408
