### ISSUE TITLE
a failed HEVC clip

### ISSUE THREAD

**Issue by nervy1982** [01org/libyami#677]
./tests/yamidecode -i /home/temp/kbl/lucas_p4/mainline/otc_build/test_I_CQP.h265
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/lucas_otc/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
yamidecode: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
Aborted (core dumped)

[test_I_CQP.zip](https://github.com/01org/libyami/files/635413/test_I_CQP.zip)

**Comment by xuguangxin** [comment]
thanks for report bug, we will check it soon.

**Comment by nervy1982** [comment]
this clip has the wrong tiles_enabled_flag and num_tile_columns_minus1 field in pps header.  if tiles_enabled_flag is disabled, this issue just disappears

**Comment by wudping** [comment]
[code](https://github.com/01org/libyami/pull/694) for this issue is submitted up, please help to review.

**Comment by xuguangxin** [comment]
this fixed by #694. thanks @nervy1982 for report
