### ISSUE TITLE
[libyami-apache] hevc decoder flush do not reset parser issue.

### ISSUE THREAD

**Issue by popkartyeah** [01org/libyami#683]
HEVC decoder need to reset parser in flush function, there will be a new stream into HEVC decoder after flush the decoder ,  but the prev stream leave some infomation in HEVC parser.

**Comment by xuguangxin** [comment]
For the container format, the sps may send only one time, flush parser will lose this information. Do you have a problem with some clips? Could you share the clips for me?

**Comment by xuguangxin** [comment]
it's fixed?

**Comment by popkartyeah** [comment]
yes, it had fixed.
