### ISSUE TITLE
[avc decoder]decoder does not report error when bitstream does not start with sps/pps

### ISSUE THREAD

**Issue by taste1981** [01org/libyami#684]
When decoding an h.264 bitstream that does not start with sps/pps, decode() does not report error when decoding nals before the first SPS/PPS.

We would expect decode call return error before the first SPS/PPS.

**Comment by taste1981** [comment]
Please consider the likely for hevc.

**Comment by xuguangxin** [comment]
Yes, we will fix hevc too.

**Comment by xuguangxin** [comment]
fixed by #690
