### ISSUE TITLE
[VP9][Encoder] '--qp' and '-f' does not work.

### ISSUE THREAD

**Issue by ghost** [01org/libyami#696]
1. yamiencode -i /media/encoderbitstreams/720x480p.yuv -s I420 -W 720 -H 480 --qp 100 -f 40 -c VP9 --rcmode CQP -o 720x480p.yuv_10.vp9
2 .mediainfo 720x480p.yuv_10.vp9
can get fps is 30.
3. set another qp value, and out stream is the same as 720x480p.yuv_10.vp9.

**Comment by wudping** [comment]
code for this issue is merged.

**Comment by ghost** [comment]
verify OK in 1.1.0 RC2 test.
