### ISSUE TITLE
libyami should pull in gtest source into a sub-folder

### ISSUE THREAD

**Issue by seanvk** [01org/libyami#707]
As we've learned from libva-utils and intel-vaapi-driver, it is far easier to simply include the gtest source in the project itself for purposes of the actual testing.

**Comment by xuguangxin** [comment]
Thanks for suggestion. I will check libva-utils and see how to do this

**Comment by xuguangxin** [comment]
I will send pull request about decoder API for vc1 and hevc. This change will conflict with the patch. I will do this change after decoder unit test merged.

**Comment by Zhziyao** [comment]
Hi, @uartie @seanvk 
According to your suggestion, I have moved the unittest files(gtest source) from encoder directory to test directory. Please help review pull request #753. If it is OK, I will move all the other subdirs' unittest files of libyami to test directory.

**Comment by uartie** [comment]
#753 does nothing to address this issue.  This issue is about adding the third-party google test source code (https://github.com/google/googletest) into this project.  See https://github.com/01org/intel-vaapi-driver/commit/1746adbb9adabd9fbee417ae3db67da599cc84e9 for an example.

**Comment by Zhziyao** [comment]
Hi, @uartie 
Thank you for your kindness advice. I have added google test source code to this project. 
Please help review pull request #774 .  Thanks.

**Comment by xuguangxin** [comment]
close this since #774 merged, thanks U.Artie and Sean
