### ISSUE TITLE
For next release, let's switch to a numbers only tag

### ISSUE THREAD

**Issue by seanvk** [01org/libyami#711]
I know we've gone back and forth on this but we should be consistent.  I'm also making sure libva's next release is numbers only as well.  That avoids the whole github archive duplicates name for tar ball.  

For next release: Use numbers only in the tag

Action Requited:  Updated packaging.  I know a pain.  But if we do it now, we are making sure all projects are consistent.

**Comment by xuguangxin** [comment]
Agree, the duplicate name generated by github is ugly. We need update Debian, Arch linux and yocto script for this.

**Comment by xuguangxin** [comment]
this fixed in 1.2.0 release, thanks Sean for suggestion
