### ISSUE TITLE
[Yami Encode] yamiencode faill for avc cqp mode with the qp=4

### ISSUE THREAD

**Issue by FocusLuo** [01org/libyami#712]
CMD as below: 
when qp=4, yami was blocked and will never returen
when qp>4, it worked well.
yamiencode -c AVC -s I420 -W 1920 -H 1080 --rcmode CQP -i  ./1080p_blue_sky.yuv -o ./1080p_blue_sky_ip_gop30_fps30_qp4.h264 --qp 4 --ipperiod 1 --intraperiod 30
[IMGUTILS @ 0x7ffc13539aa0] Picture size 0x0 is invalid
[IMGUTILS @ 0x7ffc135395b0] Picture size 0x0 is invalid
[rawvideo @ 0x1ca39a0] Could not find codec parameters for stream 0 (Video: rawvideo (I420 / 0x30323449), yuv420p, -4 kb/s): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/X11R7/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0

**Comment by xuguangxin** [comment]
Hi @FocusLuo , are you sure you use the latest version?This should fix by https://github.com/01org/libyami-utils/pull/72

**Comment by xuguangxin** [comment]
Hi @FocusLuo , any update?

**Comment by FocusLuo** [comment]
verified on the latest yami, the issue gone, so close it
