### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by arafath-mk** [01org/libyami#716]
Hi,

I got the following error while building libyami. 
```bash
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBVA... yes
checking for LIBVA_DRM... yes
checking for LIBVA_X11... no
configure: error: Package requirements (libva-x11) were not met:

No package 'libva-x11' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBVA_X11_CFLAGS
and LIBVA_X11_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Below is the command I tried to build libyami,

```bash
git clean -dxf && ./autogen.sh --prefix=$LIBYAMI_PREFIX && make -j8 && make install
```

The value of `LIBYAMI_PREFIX` is `/opt/yami/libyami`
The OS is `CentOS 7.2.1511 Minimal` (It is a server machine without GUI)

**Comment by chivakker** [comment]
On Fri, Feb 24, 2017 at 10:59 AM Arafath M <notifications@github.com> wrote:

> Hi,
>
> I got the following error while building libyami.
>
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for LIBVA... yes
> checking for LIBVA_DRM... yes
> checking for LIBVA_X11... no
> configure: error: Package requirements (libva-x11) were not met:
>
> No package 'libva-x11'
>
>
Check your libva installation as it wasn't installed with X11 support.

**Comment by arafath-mk** [comment]
Hi,
The following command was used to build and install libva.
```bash
git clean -dxf && ./autogen.sh --prefix=$VAAPI_PREFIX && make -j8 && make install
```
How may I specify to build the `libva` with `X11` support?

**Comment by chivakker** [comment]
On Fri, Feb 24, 2017 at 11:05 AM Arafath M <notifications@github.com> wrote:

> Hi,
> The following command was used to build and install libva.
>
> git clean -dxf && ./autogen.sh --prefix=$VAAPI_PREFIX && make -j8 && make install
>
> How may I specify to build the libva with X11 support?
>

By default it is on. You might missed to install the X11 development
packages and as such libva disabled it because it cannot compile it. Read
the configure output to confirm that X11 was enabled

**Comment by arafath-mk** [comment]
Thanks.. X11 development package is not installed. I will try build `libva` after installing `X11 dev packages`.
Which is the configure output file to be checked?

**Comment by chivakker** [comment]
On Fri, Feb 24, 2017 at 11:14 AM Arafath M <notifications@github.com> wrote:

> Thanks.. X11 development package is not installed. I will try build libva
> after installing X11 dev packages.
> Which is the configure output file to be checked?
>
>
It should be visible on the console like your report. Libva prints a
summary just before calling make

**Comment by arafath-mk** [comment]
Thanks.. I have disconnected and reconnected to the server machine. So, I lost the last build output from my PuTTY console.  
I was following the instructions at https://github.com/01org/libyami/wiki/Build  
The above page has incorrect git repository path for `libva` and `intel-driver` as those have been moved from the listed paths. Could you please update it?

**Comment by arafath-mk** [comment]
git clone https://github.com/01org/libva.git
git clone https://github.com/01org/intel-vaapi-driver.git

**Comment by arafath-mk** [comment]
Thanks for the help..! The build issue is solved after installing the X11 development package.  
`yum install xorg-x11-server-devel`

**Comment by xuguangxin** [comment]
hi @arafath-mk , close this since it fixed, Please reopen it if you still have the issue. thanks
