### ISSUE TITLE
V4l2decode jpeg render fail when set '-m' to 3.

### ISSUE THREAD

**Issue by feiwan1** [01org/libyami#735]
1. test cmd:
v4l2decode -i /media/yami_render/1080p_blue_sky.yuv.jpg -m 3 -w 2

2. fail info:
After run the test cmd, screen keep staying on the first frame. No error message and cmd will never exit automatically.

3. test env:
libva: 1.8.0.pre3
intel-driver: 1.8.0.pre3
libyami: tag 1.2.0-RC1
libyami-utils: tag 1.2.0-RC1

**Comment by wudping** [comment]
hi, 
This issue has been fixed by [725](https://github.com/01org/libyami/pull/725)

**Comment by feiwan1** [comment]
verified in libyami 2017Q2 RC1 release test.
