### ISSUE TITLE
[SVC-T][encode] segment fault when set layer number as 1.

### ISSUE THREAD

**Issue by feiwan1** [01org/libyami#787]
root@yami-kbl02:~# yamitranscode -i /media/encoderbitstreams/1080p_blue_sky.yuv -W 1920 -H 1080 -t 1 --layerIDs 00000000 -o test.h264
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /root/dpwu/bin_yami_verify/vaapi/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
Segmentation fault (core dumped)

test environment:
libva:1.7.3pre1
intel-vaapi-driver:1.7.3pre1

**Comment by wudping** [comment]
hi @feiwan1 ,
The patch to fix this bug is submitted in the last branch. Please help to double test, thanks.

**Comment by feiwan1** [comment]
Verified in 2nd round test, no this issue.
