### ISSUE TITLE
[media/libyami][compile] undefined reference to symbol 'vaGetDisplayDRM' when build the libyami

### ISSUE THREAD

**Issue by FocusLuo** [01org/libyami#793]
Compile line steps:
#./autogen.sh --prefix=/opt/X11R7/ --enable-tests --enable-tests-gles --enable-avformat --enable-dmabuf --enable-vp8dec --enable-vp9dec --enable-jpegdec --enable-h264dec --enable-h265dec --enable-h264enc --enable-jpegenc --enable-vp8enc --enable-vp9enc --enable-h265enc --enable-mpeg2dec --enable-vc1dec
#make -j8
#make install

/usr/bin/ld: /opt/X11R7/lib/libyami.so: undefined reference to symbol 'vaGetDisplayDRM'
/opt/X11R7/lib/libva-drm.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [simpleplayer] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/focus/media_stack_build/libyami-utils/examples'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/focus/media_stack_build/libyami-utils'
make: *** [all] Error 2
+ make install

**Comment by uartie** [comment]
Works for me.  Can you share your configure flags for libva and libyami and commitids

**Comment by uartie** [comment]
Your output shows this is libyami-utils issue, not libyami... please file issue with libyami-utils project.
