### ISSUE TITLE
Unable to enable both wayland and x11 with v4l2 enabled

### ISSUE THREAD

**Issue by uartie** [01org/libyami#794]
When configuring with `--enable-wayland --enable-x11 --enable-v4l2`, the X11 bits in `v4l2_wrapper.h` and `v4l2_wrapper.c` do not get defined.

It should be possible for both X11 and Wayland bits to coexist in the final compilation unit(s).  If that is not true for some technical reason, then configure should produce an error.

Currently, this causes libyami-utils V4L2Device.cpp to fail compilation since it expects both options can coexist.

**Comment by xuguangxin** [comment]
this will fixed by https://github.com/intel/libyami/pull/843 and https://github.com/intel/libyami-utils/pull/124

**Comment by xuguangxin** [comment]
close this since commits merged, thanks U.Artie for reporting
