### ISSUE TITLE
undefined reference to V4l2Decoder::outputPulse

### ISSUE THREAD

**Issue by uartie** [01org/libyami#795]
If `--enable-X11 --enable-v4l2 --disable-wayland --disable-egl`, then `V4l2Decoder::outputPulse` is declared but undefined.

**Comment by xuguangxin** [comment]
Hi @uartie ,

The --enable-X11 in the command line need change to --enable-x11. I tried them both, it's no problem on my system ubuntu 16.10. Could you double check it.
thanks

**Comment by xuguangxin** [comment]
Sorry, I can reproduce it now, it fixed by #802

**Comment by uartie** [comment]
yes, I meant `--enable-x11`... sorry for the typo
