### ISSUE TITLE
undefined reference to YamiV4L2_UseEglImage

### ISSUE THREAD

**Issue by uartie** [01org/libyami#796]
If `--enable-x11 --enable-v4l2 --disable-wayland --disable-egl`, then `YamiV4L2_UseEglImage` is declared but undefined.

**Comment by xuguangxin** [comment]
This no problem on my side too, could you double confirm this?
thanks

**Comment by xuguangxin** [comment]
Sorry, I can reproduce now, let me see how to fix it

**Comment by uartie** [comment]
Sorry I did not give more details earlier...

When ***libyami*** is compiled with above configure args, this causes ***libyami-utils*** compile error `undefined reference to YamiV4L2_UseEglImage` if libyami-utils is configured with `--disable-tests-gles --enable-v4l2 --enable-x11 --disable-wayland`.

The problem is that when user enables egl in libyami but not libyami-utils we need a way to ensure it still compiles for this scenario or have libyami-utils fail at configure time instead.

**Comment by uartie** [comment]
~~Sorry I did not give better details earlier...~~

~~When ***libyami*** is compiled with above configure args, this causes ***libyami-utils*** compile error `undefined reference to YamiV4L2_UseEglImage` if libyami-utils is configured with `--enable-tests-gles --enable-v4l2 --enable-x11 --disable-wayland`.~~

~~The problem is that when user **disables** egl in libyami but **enables** it in libyami-utils (with v4l2 enabled), then libyami-utils fails to compile.  Libyami-utils should be able to detect this issue at configure time and act appropriately instead of allowing the issue to propagate into compile time.~~

~~The reason I filed this issue in libyami project and not libyami-utils is because it seems we might need libyami to produce some sort of pkgconfig information so that dependent projects can detect the support properly.  Perhaps you have a better idea?~~

Please ignore this comment, it is a separate issue.

**Comment by uartie** [comment]
The issue is that `YamiV4L2_UseEglImage` gets **declared** in libyami/interface/v4l2_wrapper.h but does not get **defined** in libyami/v4l2/v4l2_wrapper.cpp because the declaration does not use the same macro guard as the definition.

**Comment by xuguangxin** [comment]
thanks @uartie , this will fixed by https://github.com/intel/libyami/pull/843
