### ISSUE TITLE
Wrong version for libyami 1.3.0

### ISSUE THREAD

**Issue by uartie** [01org/libyami#806]
https://github.com/01org/libyami/blob/libyami-1.3.0/configure.ac#L16

**Comment by YuJiankang** [comment]
artie, thanks for the reminding, I have submit patch to fix it, please help review, thanks a lot.

**Comment by YuJiankang** [comment]
it is fixed.

**Comment by uartie** [comment]
@YuJiankang the 1.3.0 release needs to include the patch that fixes this:

https://github.com/01org/libyami/releases

**Comment by uartie** [comment]
Also, do you plan to update the NEWS file for the release?

**Comment by uartie** [comment]
Please consult with @xuguangxin to ensure all necessary steps are completed before release.

**Comment by xuguangxin** [comment]
Hi @YuJiankang , please check  https://github.com/01org/libyami/commits/1.2.0  for details. thanks

**Comment by YuJiankang** [comment]
thanks artie and Guangxin, I have put the fix into the 1.3.0 release, and the NEWS is also updated. Do you have any other concern? can we close this issue? thanks a lot.
