### ISSUE TITLE
Cannot set quality of JPEG encoder.

### ISSUE THREAD

**Issue by AlexanderKomarov** [01org/libyami#818]
I use the encoder tests. If I try to change quality of JPEG for example to 90. I get failed tests. In the tests setting quality as 50 and it works. Probably the default value of quality is 50.

**Comment by uartie** [comment]
Can you share the command line you use to run these tests with different quality values?

**Comment by AlexanderKomarov** [comment]
I'm really sorry. It's my problem. I solved it. Thank you for the answer.
