### ISSUE TITLE
I can't build the yami-apache with libva2.00

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#828]
vaapipostprocess_scaler.cpp: In member function ‘virtual YamiStatus YamiMediaCodec::VaapiPostProcessScaler::process(const std::shared_ptr<VideoFrame>&, const std::shared_ptr<VideoFrame>&)’:
vaapipostprocess_scaler.cpp:129:15: error: ‘VAProcPipelineParameterBuffer {aka struct _VAProcPipelineParameterBuffer}’ has no member named ‘rotation_state’
     vppParam->rotation_state = mapToVARotationState(m_transform);
               ^~~~~~~~~~~~~~
make[2]: *** [Makefile:706：libyami_vpp_la-vaapipostprocess_scaler.lo] 错误 1

I think it may be wrong of the version of libva ?
Please make sure it can be build in all of version of libva?!

**Comment by waiter89** [comment]
请加入判断宏来区分va版本，从而兼容不同va版本

**Comment by xuguangxin** [comment]
Hi @waiter89 , @uartie 's patch added the macro you mentioned. Does it fix your issue?
