### ISSUE TITLE
Have a mean to use make check without a va-api backend

### ISSUE THREAD

**Issue by kwizart** [01org/libyami#834]
On Fedora builders (or any distro build), one cannot expect to have a va-api backend installed.

I would still like to use the make check for unit test that doesn't require any va-api backend.
I see two options:
- Using a dedicated configure option: --enable-gtest-without-vaapi-backend (or else).
The plan would be to make the vaapi decoder encoder directories optionals, so the related unitests will not be built.
- Using an env variable to avoid test using a va-api backend and make them to not error.
- Any other option ?

**Comment by xuguangxin** [comment]
Hi @kwizart , could you give me more detail about your issue?  libyami highly depends on libva, if we do not have libva, we can't do anything for decoder/encoder/vpp. So why you need to remove libva dependency in libyami?
thanks

**Comment by kwizart** [comment]
It's not about libva. libyami is expected to be compiled with VA-API enabled. It's just that I'm not supposed to have access to much hardware capability on my build environment. 

I can eventually have access to mesa VA-API backend (radeon,nouveau without the video firmware so useless). But I don't expect that the related hardware will even be present on the machine I'm building libyami (and running make check).

For some reason the intel vaapi backend cannot be fetched from Fedora directly. (It's located in RPM Fusion).

So I'd like to know if it's possible to split the tests that actually requires a va-api backend ?
Or maybe it's better to disable all tests if none or few are only relevant with an appropriate backend.

**Comment by uartie** [comment]
Tests are disabled by default in configure (or you can specify `--disable-tests` during configure).  I don't think adding support to selectively enable/disable specific tests will have much ROI since most require vaapi driver runtime... it would also introduce additional maintenance overhead.

**Comment by xuguangxin** [comment]
@kwizart , like @uartie mentioned, we have a option to disable all tests. Can this fix your issue?
thanks

**Comment by kwizart** [comment]
Sort of, the fix is to not enable tests at all in our build by default.
Let's close the issue then.
Thanks

**Comment by xuguangxin** [comment]
thanks, @kwizart , please report any issue if you found.
