### ISSUE TITLE
Build OCL fail in the newest linux system

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#850]
../ocl/oclcontext.cpp: In member function ‘bool YamiMediaCodec::OclContext::init()’:
../ocl/oclcontext.cpp:100:77: error: ‘_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)’ is deprecated [-Werror=deprecated-declarations]
     m_queue = clCreateCommandQueue(m_context, m_device->m_device, 0, &status);
                                                                             ^
In file included from /usr/include/CL/opencl.h:47:0,
                 from ../ocl/oclcontext.h:22,
                 from ../ocl/oclcontext.cpp:22:
/usr/include/CL/cl.h:1443:1: note: declared here
 clCreateCommandQueue(cl_context                     /* context */,
 ^~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

**Comment by xuguangxin** [comment]
Hi @waiter89 , 
this because you use OpenCL2.0. We did not test against 2.0 before.
Which opencl implementation you used? Beignet?
