### ISSUE TITLE
decode h264 SIGSEGV

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#852]
[hikvideo.tar.gz](https://github.com/intel/libyami/files/2021751/hikvideo.tar.gz)
decode the video from hikvision SIGSEGV

**Comment by xuguangxin** [comment]
Hi @waiter89 , 
I tried latest libva and libyami. I can't reproduce y our issue. Could you share more information with us? like platform, libva/libyami version? Could you try latest code?

thanks
