### ISSUE TITLE
VP9 encode support 

### ISSUE THREAD

**Issue by JackXu2** [01org/libyami#857]
1.In media sdk both windows and linux, they does not support VP9 encode with below 8gen CPU. only windows media sdk support by cannon lake.
2. how libyami support VP9 encode? which CPU support this VP9 encode?
3. how about performance for the VP9 encode with libyami?

**Comment by xuguangxin** [comment]
1. only kbl+ has vp9 encoder
2.  We are not authorized to public performance data, you can use yamitranscode to test on your platform.
thanks

**Comment by JackXu2** [comment]
Thanks, do you know the window media sdk support vp9 encoder on kbl+.
and it seems linux media sdk does not support vp9 encode for all platform?
https://github.com/Intel-Media-SDK/MediaSDK

**Comment by xuguangxin** [comment]
Do not know why, we are not involve the msdk development, you may need ask msdk team.

thanks

**Comment by JackXu2** [comment]
thanks
