### ISSUE TITLE
How to turn off debug messages

### ISSUE THREAD

**Issue by EwanRoycroft** [01org/libyami#887]
I would like to turn off debug messaging from yami but cannot find how to do this.

I can see some of my V4L2 ioctls are triggering `ERROR` -> `YAMI_DEBUG_MESSAGE` -> `yamiMessage` and wonder if there is a configuration/build argument to turn this off.

Edit:
I notice that `yamiMessage` only triggers if `yamiLogFlag >= YAMI_LOG_ERROR`, I assume that error messages are not turned off by `--enable-debug=no`?

**Comment by EwanRoycroft** [comment]
Found the solution. 

#70: Log levels are set with the `LIBYAMI_LOG_LEVEL` environment variable at runtime, not during configuration/build.

**Comment by xuguangxin** [comment]
yes, you are right.
